## Content
1. Learn HTML and CSS Basic : https://www.w3schools.com/html/ and https://www.w3schools.com/css/default.asp
2. Web Scrapping concept
3. Create Scrapping link
4. link refference : https://tedboy.github.io/bs4_doc/6_searching_the_tree.html#kinds-of-filters

In [ ]:
pip install selenium

Collecting selenium
  Downloading selenium-4.30.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.11/dist-packages (from urllib3[socks]<3,>=1.26->selenium) (2.3.0)
Collecting trio~=0.17 (from selenium)
  Downloading trio-0.29.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket~=0.9 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.11/dist-packages (from selenium) (2025.1.31)
Requirement already satisfied: typing_extensions~=4.9 in /usr/local/lib/python3.11/dist-packages (from selenium) (4.12.2)
Requirement already satisfied: websocket-client~=1.8 in /usr/local/lib/python3.11/dist-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium) (3.10)
Collecting outcome (from trio~=0.17->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium)
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Downloading selenium-4.30.0-py3-none-any.whl (9.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 24.9 MB/s eta 0:00:00
Downloading trio-0.29.0-py3-none-any.whl (492 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 492.9/492.9 kB 21.3 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, outcome, trio, trio-websocket, selenium
Successfully installed outcome-1.3.0.post0 selenium-4.30.0 trio-0.29.0 trio-websocket-0.12.2 wsproto-1.2.0

In [ ]:
# import library yang dibutuhkan
import requests
from bs4 import BeautifulSoup
import time
from selenium import webdriver
import pandas as pd
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import os
pd.options.display.max_colwidth = 300

### Scrapping Villa
1. link utama : https://www.bukitvista.com/property-type/villa

In [ ]:
url_villa = "https://www.bukitvista.com/property-type/villa" # API
#driver = webdriver.Firefox()
# jika running di local, maka code option dibawah ini ga perlu di running lagi, cukup 1x diatas saja
option = webdriver.ChromeOptions()
option.add_argument("--start-maximized")

#=============================
# uncomment untuk running code dibawah ini jika run di google collab
option.add_argument("--headless")
option.add_argument("--disable-gpu")
option.add_argument("--no-sandbox")
option.add_argument("--remote-debugging-port=9230")
# comment 4 code diatas jika running di local / jupyter notebook dsb
#=============================

driver_villa = webdriver.Chrome(options=option)
driver_villa.get(url_villa)
# Membuat objek BeautifulSoup dari konten HTML
soup = BeautifulSoup(driver_villa.page_source, "html.parser")

In [ ]:
print(soup)

<html class="target webanimations no-multiplebgs supports subpixelfont cssvalid cssvmaxunit cssvwunit textshadow requestanimationframe raf cssanimations csspseudoanimations ellipsis cssmask no-overflowscrolling cssresize csstransforms3d csstransitions webpanimation" lang="en-US" prefix="og: https://ogp.me/ns#" style="transform: none;"><head>
<!-- Google Tag Manager -->
<script async="" src="https://static.hotjar.com/c/hotjar-2388587.js?sv=7" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-TFNZ3GNYZS&amp;l=dataLayer&amp;cx=c&amp;gtm=45He53q1h1v843403130za200&amp;tag_exp=102482433~102788824~102803279~102813109~102887799~102926062~102975948" type="text/javascript"></script><script crossorigin="anonymous" data-hsjs-env="prod" data-hsjs-hublet="na1" data-hsjs-portal="43966362" data-leadin-env="prod" data-leadin-portal-id="43966362" data-loader="hs-scriptloader" id="CollectedForms-43966362" src="https://js.hscollectedforms.net/collectedforms.js" type="text/javascript"></script><script id="hs-analytics" src="https://js.hs-analytics.net/analytics/1743296400000/43966362.js" type="text/javascript"></script><script data-cookieconsent="ignore" data-hs-ignore="true" data-hsjs-env="prod" data-hsjs-hublet="na1" data-hsjs-portal="43966362" data-loader="hs-scriptloader" id="cookieBanner-43966362" src="https://js.hs-banner.com/v2/43966362/banner.js" type="text/javascript"></script><script async="" src="https://connect.facebook.net/signals/config/272765961174483?v=2.9.191&amp;r=stable&amp;domain=www.bukitvista.com&amp;hme=ae6b81567baef13f3d085d995659a5ae4a9de556ad2f6e24bef863fd4ce78d6a&amp;ex_m=72%2C126%2C111%2C115%2C63%2C5%2C104%2C71%2C17%2C100%2C92%2C52%2C56%2C180%2C183%2C195%2C191%2C192%2C194%2C30%2C105%2C54%2C79%2C193%2C175%2C178%2C188%2C189%2C196%2C137%2C42%2C201%2C198%2C199%2C35%2C150%2C16%2C51%2C205%2C204%2C139%2C19%2C41%2C1%2C44%2C67%2C68%2C69%2C73%2C96%2C18%2C15%2C99%2C95%2C94%2C112%2C53%2C114%2C40%2C113%2C31%2C97%2C27%2C176%2C179%2C147%2C29%2C75%2C0%2C98%2C88%2C58%2C86%2C34%2C84%2C85%2C91%2C48%2C47%2C90%2C38%2C12%2C13%2C14%2C7%2C8%2C26%2C23%2C24%2C59%2C64%2C66%2C77%2C55%2C106%2C28%2C78%2C10%2C9%2C82%2C49%2C22%2C108%2C107%2C109%2C101%2C11%2C21%2C3%2C39%2C76%2C20%2C6%2C93%2C83%2C45%2C33%2C36%2C89%2C4%2C87%2C246%2C173%2C124%2C162%2C155%2C2%2C37%2C65%2C43%2C110%2C46%2C81%2C70%2C116%2C62%2C61%2C32%2C102%2C60%2C57%2C50%2C80%2C74%2C25%2C103%2C117"></script><script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-N33B4BS"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-N33B4BS"></script><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','GTM-N33B4BS');</script>
<!-- End Google Tag Manager -->
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://gmpg.org/xfn/11" rel="profile"/>
<meta content="telephone=no" name="format-detection"/>
<!-- Search Engine Optimization by Rank Math - https://rankmath.com/ -->
<title>Villa - Bukit Vista</title>
<meta content="follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large" name="robots"/>
<link href="https://www.bukitvista.com/property-type/villa" rel="canonical"/>
<link href="https://www.bukitvista.com/property-type/villa/page/2" rel="next"/>
<meta content="en_US" property="og:locale"/>
<meta content="article" property="og:type"/>
<meta content="Villa - Bukit Vista" property="og:title"/>
<meta content="https://www.bukitvista.com/property-type/villa" property="og:url"/>
<meta content="Bukit Vista" property="og:site_name"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="Villa - Bukit Vista" name="twitter:title"/>
<meta content="Properties" name="twitter:label1"/>
<meta content="35" name="twitter:data1"/>
<script class="rank-math-schema" type="application/ld+json">{"@context":"https://schema.org","@graph":[{"@type":"LocalBusiness","@id":"https://www.bukitvista.com/#organization","name":"Bukit Vista","url":"https://www.bukitvista.com","logo":{"@type":"ImageObject","@id":"https://www.bukitvista.com/#logo","url":"https://www.bukitvista.com/wp-content/uploads/2022/09/cropped-Bukit-Vista-Logo.png","contentUrl":"https://www.bukitvista.com/wp-content/uploads/2022/09/cropped-Bukit-Vista-Logo.png","caption":"Bukit Vista","inLanguage":"en-US","width":"512","height":"512"},"openingHours":["Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday 09:00-17:00"],"image":{"@id":"https://www.bukitvista.com/#logo"}},{"@type":"WebSite","@id":"https://www.bukitvista.com/#website","url":"https://www.bukitvista.com","name":"Bukit Vista","publisher":{"@id":"https://www.bukitvista.com/#organization"},"inLanguage":"en-US"},{"@type":"BreadcrumbList","@id":"https://www.bukitvista.com/property-type/villa#breadcrumb","itemListElement":[{"@type":"ListItem","position":"1","item":{"@id":"https://www.bukitvista.com","name":"Home"}},{"@type":"ListItem","position":"2","item":{"@id":"https://www.bukitvista.com/property-type/villa","name":"Villa"}}]},{"@type":"CollectionPage","@id":"https://www.bukitvista.com/property-type/villa#webpage","url":"https://www.bukitvista.com/property-type/villa","name":"Villa - Bukit Vista","isPartOf":{"@id":"https://www.bukitvista.com/#website"},"inLanguage":"en-US","breadcrumb":{"@id":"https://www.bukitvista.com/property-type/villa#breadcrumb"}}]}</script>
<!-- /Rank Math WordPress SEO plugin -->
<script id="pys-version-script" type="application/javascript">console.log('PixelYourSite Free version 9.5.2');</script>
<link href="//js.hs-scripts.com" rel="dns-prefetch"/>
<link href="//www.bukitvista.com" rel="dns-prefetch"/>
<link href="//fonts.googleapis.com" rel="dns-prefetch"/>
<link href="//www.googletagmanager.com" rel="dns-prefetch"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://www.bukitvista.com/feed" rel="alternate" title="Bukit Vista » Feed" type="application/rss+xml"/>
<link href="https://www.bukitvista.com/comments/feed" rel="alternate" title="Bukit Vista » Comments Feed" type="application/rss+xml"/>
<link href="https://www.bukitvista.com/property-type/villa/feed" rel="alternate" title="Bukit Vista » Villa Type Feed" type="application/rss+xml"/>
<script type="text/javascript">
window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/14.0.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/14.0.0\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/www.bukitvista.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=6.2.6"}};
/*! This file is auto-generated */
!function(e,a,t){var n,r,o,i=a.createElement("canvas"),p=i.getContext&&i.getContext("2d");function s(e,t){p.clearRect(0,0,i.width,i.height),p.fillText(e,0,0);e=i.toDataURL();return p.clearRect(0,0,i.width,i.height),p.fillText(t,0,0),e===i.toDataURL()}function c(e){var t=a.createElement("script");t.src=e,t.defer=t.type="text/javascript",a.getElementsByTagName("head")[0].appendChild(t)}for(o=Array("flag","emoji"),t.supports={everything:!0,everythingExceptFlag:!0},r=0;r<o.length;r++)t.supports[o[r]]=function(e){if(p&&p.fillText)switch(p.textBaseline="top",p.font="600 32px Arial",e){case"flag":return s("\ud83c\udff3\ufe0f\u200d\u26a7\ufe0f","\ud83c\udff3\ufe0f\u200b\u26a7\ufe0f")?!1:!s("\ud83c\uddfa\ud83c\uddf3","\ud83c\uddfa\u200b\ud83c\uddf3")&&!s("\ud83c\udff4\udb40\udc67\udb40\udc62\udb40\udc65\udb40\udc6e\udb40\udc67\udb40\udc7f","\ud83c\udff4\u200b\udb40\udc67\u200b\udb40\udc62\u200b\udb40\udc65\u200b\udb40\udc6e\u200b\udb40\udc67\u200b\udb40\udc7f");case"emoji":return!s("\ud83e\udef1\ud83c\udffb\u200d\ud83e\udef2\ud83c\udfff","\ud83e\udef1\ud83c\udffb\u200b\ud83e\udef2\ud83c\udfff")}return!1}(o[r]),t.supports.everything=t.supports.everything&&t.supports[o[r]],"flag"!==o[r]&&(t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&t.supports[o[r]]);t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&!t.supports.flag,t.DOMReady=!1,t.readyCallback=function(){t.DOMReady=!0},t.supports.everything||(n=function(){t.readyCallback()},a.addEventListener?(a.addEventListener("DOMContentLoaded",n,!1),e.addEventListener("load",n,!1)):(e.attachEvent("onload",n),a.attachEvent("onreadystatechange",function(){"complete"===a.readyState&&t.readyCallback()})),(e=t.source||{}).concatemoji?c(e.concatemoji):e.wpemoji&&e.twemoji&&(c(e.twemoji),c(e.wpemoji)))}(window,document,window._wpemojiSettings);
</script><script defer="" src="https://www.bukitvista.com/wp-includes/js/wp-emoji-release.min.js?ver=6.2.6" type="text/javascript"></script>
<style type="text/css">
img.wp-smiley,
img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 0.07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
</style>
<link href="https://www.bukitvista.com/wp-includes/css/dist/block-library/style.min.css?ver=6.2.6" id="wp-block-library-css" media="all" rel="stylesheet" type="text/css"/>
<style id="rank-math-toc-block-style-inline-css" type="text/css">
.wp-block-rank-math-toc-block nav ol{counter-reset:item}.wp-block-rank-math-toc-block nav ol li{display:block}.wp-block-rank-math-toc-block nav ol li:before{content:counters(item, ".") " ";counter-increment:item}

</style>
<style id="joinchat-button-style-inline-css" type="text/css">
.wp-block-joinchat-button{border:none!important;text-align:center}.wp-block-joinchat-button figure{display:table;margin:0 auto;padding:0}.wp-block-joinchat-button figcaption{font:normal normal 400 .6em/2em var(--wp--preset--font-family--system-font,sans-serif);margin:0;padding:0}.wp-block-joinchat-button .joinchat-button__qr{background-color:#fff;border:6px solid #25d366;border-radius:30px;box-sizing:content-box;display:block;height:200px;margin:auto;overflow:hidden;padding:10px;width:200px}.wp-block-joinchat-button .joinchat-button__qr canvas,.wp-block-joinchat-button .joinchat-button__qr img{display:block;margin:auto}.wp-block-joinchat-button .joinchat-button__link{align-items:center;background-color:#25d366;border:6px solid #25d366;border-radius:30px;display:inline-flex;flex-flow:row nowrap;justify-content:center;line-height:1.25em;margin:0 auto;text-decoration:none}.wp-block-joinchat-button .joinchat-button__link:before{background:transparent var(--joinchat-ico) no-repeat center;background-size:100%;content:"";display:block;height:1.5em;margin:-.75em .75em -.75em 0;width:1.5em}.wp-block-joinchat-button figure+.joinchat-button__link{margin-top:10px}@media (orientation:landscape)and (min-height:481px),(orientation:portrait)and (min-width:481px){.wp-block-joinchat-button.joinchat-button--qr-only figure+.joinchat-button__link{display:none}}@media (max-width:480px),(orientation:landscape)and (max-height:480px){.wp-block-joinchat-button figure{display:none}}

</style>
<link href="https://www.bukitvista.com/wp-includes/css/classic-themes.min.css?ver=6.2.6" id="classic-theme-styles-css" media="all" rel="stylesheet" type="text/css"/>
<style id="global-styles-inline-css" type="text/css">

In [ ]:
for tag in soup.find_all(True):
    print(tag.name)

html
head
script
script
script
script
script
script
script
script
script
script
meta
meta
link
meta
title
meta
link
link
meta
meta
meta
meta
meta
meta
meta
meta
meta
script
script
link
link
link
link
link
link
link
link
script
script
style
link
style
style
link
style
link
link
link
link
link
link
link
link
link
link
link
link
style
link
style
link
link
link
link
noscript
link
script
script
script
script
script
script
link
link
link
link
meta
meta
meta
script
script
script
link
meta
script
script
script
link
link
link
meta
style
style
style
style
script
body
noscript
iframe
noscript
iframe
svg
defs
filter
fecolormatrix
fecomponenttransfer
fefuncr
fefuncg
fefuncb
fefunca
fecomposite
svg
defs
filter
fecolormatrix
fecomponenttransfer
fefuncr
fefuncg
fefuncb
fefunca
fecomposite
svg
defs
filter
fecolormatrix
fecomponenttransfer
fefuncr
fefuncg
fefuncb
fefunca
fecomposite
svg
defs
filter
fecolormatrix
fecomponenttransfer
fefuncr
fefuncg
fefuncb
fefunca
fecomposite
svg
defs
filter
fecolormatrix
fecomponenttransfer
fefuncr
fefuncg
fefuncb
fefunca
fecomposite
svg
defs
filter
fecolormatrix
fecomponenttransfer
fefuncr
fefuncg
fefuncb
fefunca
fecomposite
svg
defs
filter
fecolormatrix
fecomponenttransfer
fefuncr
fefuncg
fefuncb
fefunca
fecomposite
svg
defs
filter
fecolormatrix
fecomponenttransfer
fefuncr
fefuncg
fefuncb
fefunca
fecomposite
div
div
ul
li
a
li
a
span
i
ul
li
a
span
i
ul
li
a
span
i
ul
li
a
li
a
li
a
li
a
span
i
ul
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
span
i
ul
li
a
span
i
ul
li
a
li
a
span
i
ul
li
a
li
a
li
a
span
i
ul
li
a
span
i
ul
li
a
li
a
li
a
li
a
li
a
span
i
ul
li
a
li
a
li
a
span
i
ul
li
a
span
i
ul
li
a
li
a
li
a
li
a
span
i
ul
li
a
span
i
ul
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
span
i
ul
li
a
span
i
ul
li
a
li
a
li
a
span
i
ul
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
div
div
div
div
div
a
img
a
img
a
img
a
img
a
img
a
img
a
img
a
img
div
div
img
span
span
nav
main
header
div
div
div
div
div
a
img
nav
ul
li
a
li
a
ul
li
a
ul
li
a
ul
li
a
li
a
li
a
li
a
ul
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
ul
li
a
ul
li
a
li
a
ul
li
a
li
a
li
a
ul
li
a
ul
li
a
li
a
li
a
li
a
li
a
ul
li
a
li
a
li
a
ul
li
a
ul
li
a
li
a
li
a
li
a
ul
li
a
ul
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
ul
li
a
ul
li
a
li
a
li
a
ul
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
div
div
div
div
div
a
img
a
img
a
img
a
img
a
img
a
img
a
img
a
img
div
div
img
span
span
div
ul
div
div
button
i
div
div
a
img
div
section
div
div
div
nav
ol
li
a
span
li
div
div
h1
div
ul
li
a
i
li
a
i
div
div
article
div
div
div
div
div
div
div
select
option
option
option
option
option
option
option
option
option
button
div
div
div
div
div
ul
div
div
div
div
div
span
div
a
a
a
a
a
a
a
a
ul
li
ul
li
span
i
li
span
i
li
span
i
div
div
a
img
div
div
button
div
div
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
button
div
div
div
a
a
a
a
a
a
a
a
h2
a
ul
li
address
ul
li
i
span
span
li
i
span
span
li
span
a
div
i
a
div
i
div
div
i
a
div
i
div
div
div
div
span
div
a
a
a
a
a
a
a
a
ul
li
ul
li
span
i
li
span
i
li
span
i
div
div
a
img
div
div
button
div
div
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
button
div
div
div
a
a
a
a
a
a
a
a
h2
a
ul
li
address
ul
li
i
span
span
li
i
span
span
li
span
a
div
i
a
div
i
div
div
i
a
div
i
div
div
div
div
span
div
a
a
a
a
a
a
a
a
ul
li
ul
li
span
i
li
span
i
li
span
i
div
div
a
img
div
div
button
div
div
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
button
div
div
div
a
a
a
a
a
a
a
a
h2
a
ul
li
address
ul
li
i
span
span
li
i
span
span
li
span
a
div
i
a
div
i
div
div
i
a
div
i
div
div
div
div
span
div
a
a
ul
li
ul
li
span
i
li
span
i
li
span
i
div
div
a
img
div
div
button
div
div
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
button
div
div
div
a
a
h2
a
ul
li
address
ul
li
i
span
span
li
i
span
span
li
span
a
div
i
a
div
i
div
div
i
a
div
i
div
div
div
div
span
div
a
a
a
a
a
a
ul
li
ul
li
span
i
li
span
i
li
span
i
div
div
a
img
div
div
button
div
div
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
button
div
div
div
a
a
a
a
a
a
h2
a
ul
li
address
ul
li
i
span
span
li
i
span
span
li
span
a
div
i
a
div
i
div
div
i
a
div
i
div
div
div
div
span
div
a
a
a
a
ul
li
ul
li
span
i
li
span
i
li
span
i
div
div
a
img
div
div
button
div
div
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
button
div
div
div
a
a
a
a
h2
a
ul
li
address
ul
li
i
span
span
li
i
span
span
li
span
a
div
i
a
div
i
div
div
i
a
div
i
div
div
div
div
span
div
a
a
a
a
ul
li
ul
li
span
i
li
span
i
li
span
i
div
div
a
img
div
div
button
div
div
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
button
div
div
div
a
a
a
a
h2
a
ul
li
address
ul
li
i
span
span
li
i
span
span
li
span
a
div
i
a
div
i
div
div
i
a
div
i
div
div
div
div
span
div
a
a
a
a
ul
li
ul
li
span
i
li
span
i
li
span
i
div
div
a
img
div
div
button
div
div
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
button
div
div
div
a
a
a
a
h2
a
ul
li
address
ul
li
i
span
span
li
i
span
span
li
span
a
div
i
a
div
i
div
div
i
a
div
i
div
div
div
div
span
div
a
a
a
ul
li
ul
li
span
i
li
span
i
li
span
i
div
div
a
img
div
div
button
div
div
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
button
div
div
div
a
a
a
h2
a
ul
li
address
ul
li
i
span
span
li
i
span
span
li
span
a
div
i
a
div
i
div
div
i
a
div
i
div
nav
ul
li
a
i
li
a
span
li
a
li
a
li
a
li
a
i
div
div
aside
div
div
h3
div
div
button
div
div
div
div
div
div
a
img
div
a
a
a
a
a
span
ul
li
address
div
div
div
div
a
img
div
a
a
a
a
a
a
a
span
ul
li
address
div
div
div
div
a
img
div
a
a
a
a
a
a
a
span
ul
li
address
div
div
div
div
a
img
div
a
a
a
a
a
a
a
span
ul
li
address
div
div
div
div
a
img
div
a
a
span
ul
li
address
div
div
div
div
a
img
div
a
a
a
a
a
span
ul
li
address
div
div
div
div
a
img
div
a
a
a
a
a
a
a
span
ul
li
address
div
div
div
div
a
img
div
a
a
a
a
a
a
a
span
ul
li
address
div
div
div
div
a
img
div
a
a
a
a
a
a
a
span
ul
li
address
div
div
div
div
a
img
div
a
a
span
ul
li
address
div
div
div
div
a
img
div
a
a
a
a
a
span
ul
li
address
button
ul
li
button
li
button
li
button
li
button
li
button
div
div
h3
div
ul
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
div
div
h3
div
ul
li
a
li
a
li
a
footer
div
div
div
div
div
img
div
h5
strong
br
div
p
a
strong
span
div
p
a
strong
span
div
p
br
a
strong
span
div
div
div
h3
div
ul
li
a
ul
li
a
li
a
li
a
ul
li
a
li
a
ul
li
a
li
a
li
a
li
a
div
div
div
h3
div
ul
li
a
li
a
li
a
li
a
div
div
div
h3
div
ul
li
a
li
a
div
div
div
div
div
ul
li
a
li
a
li
a
li
a
div
a
i
div
button
span
i
p
strong
div
a
button
div
div
div
div
div
ul
li
a
button
span
div
div
div
div
form
div
div
div
input
div
div
input
div
div
label
input
span
a
input
input
input
input
button
span
div
button
span
button
span
img
div
div
div
div
div
div
h5
button
span
div
div
p
form
div
input
input
input
button
span
div
div
div
div
div
div
div
div
div
img
noscript
img
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
p
div
div
script
noscript
img
iframe
iframe
script
iframe

In [ ]:
div_containers = soup.findAll('div', attrs={'class':"d-flex align-items-center h-100"})
print(div_containers)

[<div class="d-flex align-items-center h-100">
<div class="item-header">
<span class="label-featured label">Featured</span> <div class="labels-wrap labels-right">
<a class="label-status label status-color-887" href="https://www.bukitvista.com/status/bali-vacation-rental">
					Bali Vacation Rental
				</a><a class="label-status label status-color-268" href="https://www.bukitvista.com/status/group-friendly-stay">
					Group Friendly Stay
				</a><a class="label-status label status-color-269" href="https://www.bukitvista.com/status/long-stay-trend-property">
					Long Stay Trend Property
				</a><a class="label-status label status-color-43" href="https://www.bukitvista.com/status/new-listing">
					New Listing
				</a><a class="label-status label status-color-293" href="https://www.bukitvista.com/status/private">
					Private
				</a><a class="label-status label status-color-888" href="https://www.bukitvista.com/status/private-pool">
					Private Pool
				</a><a class="label-status label status-color-141" href="https://www.bukitvista.com/status/top-trending">
					Top Trending
				</a><a class="hz-label label label-color-117" href="https://www.bukitvista.com/label/new">
					New
				</a>
</div>
<ul class="item-price-wrap hide-on-list">
<li class="item-price item-price-text">$258 per 2 nights</li></ul> <ul class="item-tools">
<li class="item-tool item-preview">
<span class="hz-show-lightbox-js" data-listid="103653" data-original-title="Preview" data-placement="top" data-toggle="tooltip" title="">
<i class="houzez-icon icon-expand-3"></i>
</span><!-- item-tool-favorite -->
</li><!-- item-tool -->
<li class="item-tool item-favorite">
<span class="add-favorite-js item-tool-favorite" data-listid="103653" data-original-title="Favourite" data-placement="top" data-toggle="tooltip" title="">
<i class="houzez-icon icon-love-it"></i>
</span><!-- item-tool-favorite -->
</li><!-- item-tool -->
<li class="item-tool item-compare">
<span class="houzez_compare compare-103653 item-tool-compare show-compare-panel" data-listing_id="103653" data-listing_image="https://bukitvista-wordpress-storage.s3.us-east-2.amazonaws.com/wp-content/uploads/2025/02/08103716/download-1-592x444.webp" data-original-title="Add to Compare" data-placement="top" data-toggle="tooltip" title="">
<i class="houzez-icon icon-add-circle"></i>
</span><!-- item-tool-compare -->
</li><!-- item-tool -->
</ul><!-- item-tools -->
<div class="listing-image-wrap">
<div class="listing-thumb">
<a class="listing-featured-thumb hover-effect" href="https://www.bukitvista.com/property/uluwatu-modern-boho-villa-near-nyang-nyang-beach-2" target="_self">
<img alt="" class="img-fluid wp-post-image" decoding="async" height="444" loading="lazy" sizes="(max-width: 592px) 100vw, 592px" src="https://bukitvista-wordpress-storage.s3.us-east-2.amazonaws.com/wp-content/uploads/2025/02/08103716/download-1-592x444.webp" srcset="https://bukitvista-wordpress-storage.s3.us-east-2.amazonaws.com/wp-content/uploads/2025/02/08103716/download-1-592x444.webp 592w, https://bukitvista-wordpress-storage.s3.us-east-2.amazonaws.com/wp-content/uploads/2025/02/08103716/download-1-584x438.webp 584w, https://bukitvista-wordpress-storage.s3.us-east-2.amazonaws.com/wp-content/uploads/2025/02/08103716/download-1-120x90.webp 120w" width="592"/> </a><!-- hover-effect -->

<ipython-input-6-dcaa32b47578>:1: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  div_containers = soup.findAll('div', attrs={'class':"d-flex align-items-center h-100"})

### One Page

In [ ]:
bathroom_villa = [] # list kosong
for container in div_containers:
    bathroom = container.find('li', attrs={"class":'h-baths'}).text
    print(bathroom) # ngeluarin nilai
    bathroom_villa.append((bathroom)) # bathroom_villa -> json list
# Parser html documents
bathroom_villa = pd.DataFrame(bathroom_villa, columns=['kamar mandi'])
bathroom_villa

Baths: 2
Baths: 3
Baths: 4
Baths: 4
Baths: 2
Baths: 2.5
Baths: 2
Baths: 3.5
Baths: 2

  kamar mandi
0    Baths: 2
1    Baths: 3
2    Baths: 4
3    Baths: 4
4    Baths: 2
5  Baths: 2.5
6    Baths: 2
7  Baths: 3.5
8    Baths: 2

## Multiple Page

In [ ]:
# range(start,end,step) -> step = 1
for i in range(1,5):
    print(i)

1
2
3
4

In [ ]:
pages = ['page1','kolom_page1','alamat_page2','address_page_3']

for page in pages:
  print(page)

page1
kolom_page1
alamat_page2
address_page_3

In [ ]:
for page in range(1, 5):  # Mengiterasi melalui 4 halaman
    url = f'https://www.bukitvista.com/property-type/villa/page/{page}'
    print(url)

https://www.bukitvista.com/property-type/villa/page/1
https://www.bukitvista.com/property-type/villa/page/2
https://www.bukitvista.com/property-type/villa/page/3
https://www.bukitvista.com/property-type/villa/page/4

In [ ]:
titles = []  # List untuk menyimpan judul

for page in range(1, 5):  # Mengiterasi melalui 4 halaman
    url = f'https://www.bukitvista.com/property-type/villa/page/{page}'  # Ganti URL dengan URL sebenarnya
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser') # Parser html documents
    #code diatas ialah untuk multiple page

    #define container terluar
    div_containers = soup.findAll('div', attrs={'class': 'd-flex align-items-center h-100'})

    for container in div_containers:
        review = container.find('h2', attrs={'class': 'item-title'})
        if review:
            titles.append(review.text.strip())

# Membuat dataframe dari list judul
df_villa_title = pd.DataFrame({'title': titles})
print('total properties yang didapat : ', len(df_villa_title)) #validation data
# Menampilkan dataframe
df_villa_title.head()

<ipython-input-10-f0a9c839e1f1>:10: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  div_containers = soup.findAll('div', attrs={'class': 'd-flex align-items-center h-100'})

total properties yang didapat :  35

                                                          title
0              Uluwatu Modern Boho Villa Near Nyang Nyang Beach
1            Bingin Beach Hideaway: Group Villa with Pool & BBQ
2   4-Bedroom Mediterranean Luxury Villa with Ubud Rooftop View
3  Luxurious 3-Bedroom Nusa Dua Seafront Villa w/ Private Beach
4               Grand Villa Retreat w/ Pool & Garden in Ungasan

In [ ]:
df_villa_title

                                                                title
0                    Uluwatu Modern Boho Villa Near Nyang Nyang Beach
1                  Bingin Beach Hideaway: Group Villa with Pool & BBQ
2         4-Bedroom Mediterranean Luxury Villa with Ubud Rooftop View
3        Luxurious 3-Bedroom Nusa Dua Seafront Villa w/ Private Beach
4                     Grand Villa Retreat w/ Pool & Garden in Ungasan
5    Surfer’s Villa 4 Mins to Bingin & Dreamland Beach by Bukit Vista
6    Private Pool Villa Minutes from Bingin Surf Haven by Bukit Vista
7    Ungasan Exquisite Villa w/ Rooftop & Private Pool by Bukit Vista
8                        Sun-Soaked Canggu Villa Perfect for Families
9                  Sunny Exquisite Umalas Villa: 20 Minutes to Canggu
10                     Dazzling Villa with Pool and Rooftop in Bingin
11                  Sun-Soaked 2BR Villa w/ Pool 15-Min Ride to Beach
12                    Voguish Penthouse with Rooftop Pool Near Canggu
13                      Artisanal Berawa Villa: 11 mins Ride to Beach
14                     Private Ungasan Hideaway Villa with Pool Oasis
15                     Sunny Tropical Luxe Villa in Ungasan with Pool
16                      Dreamy Haven w/ Pool | 300m from Bingin Beach
17                   Ungasan Haven: 3BR Villa w/ Private Pool Retreat
18                 Unwind in Tabanan Remote Jungle with Infinity Pool
19                                     Villa by Rice Fields in Canggu
20                    Group Getaway: Cozy Villa w/Pool Near GWK Park￼
21                    Tranquil Kutuh Villa w/ Pool – Ideal for Groups
22                            Spacious New Tropical Villa w/ GWK View
23                  3BR Javanese Traditional Relaxing Villa with Pool
24                 Bukit Vista | Heritage Joglo Villa w/ Private Pool
25                 Bohemian Beachfront Surf Villa by the Bingin Beach
26                 Bukit Vista | Heritage Joglo Villa w/ Private Pool
27                 Bukit Vista | Stunning 3BR Villa Near Padang Beach
28                      Quaint & Homey Balinese Villa w/ Private Pool
29                   Tranquil 3BR Villa in Jimbaran with Wi-Fi + Pool
30                    Lovely Private Pool Villa in Strategic Location
31                   Authentic Balinese Cabin near Beach | sterilized
32                   Family Holiday House w/ Private Pool in Jimbaran
33  4BR Homey Villa in Uluwatu | Kitchen + Wifi + Pool by Bukit Vista
34                  Picturesque Cottage in the Heart of Ubud’s Nature

In [ ]:
data_address = []  # List untuk menyimpan judul

for page in range(1, 5):  # Mengiterasi melalui 4 halaman
    url = f'https://www.bukitvista.com/property-type/villa/page/{page}'  # Ganti URL dengan URL sebenarnya
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    div_containers = soup.findAll('div', attrs={'class': 'd-flex align-items-center h-100'})

    for container in div_containers:
        address = container.find('address', attrs={"class":'item-address'})
        if address:
            data_address.append(address.text.strip())

# Membuat dataframe dari list judul
df_villa_address = pd.DataFrame({'alamat': data_address})
print('total properties yang didapat : ', len(df_villa_address))
# Menampilkan dataframe
df_villa_address

<ipython-input-12-df04b01c0e8a>:7: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  div_containers = soup.findAll('div', attrs={'class': 'd-flex align-items-center h-100'})

total properties yang didapat :  35

                                                                                                      alamat
0                                Jl. Batu Nunggul No.1, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361
1             Jl. Pantai Cemongkak Gg. Samuh Sari No.2, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361
2                                            Jl. Suweta, Ubud, Kecamatan Ubud, Kabupaten Gianyar, Bali 80571
3
4                         Jl. Pantai Balangan I No.9x, Ungasan, Kec. Kuta Sel., Kabupaten Badung, Bali 80361
5                                               Pecatu, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia
6                                               Pecatu, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia
7                                              Ungasan, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia
8                                             Tibubeneng, Kuta Utara, Badung, Bali, Nusa Tenggara, Indonesia
9
10
11                                                                  Denpasar, Bali, Nusa Tenggara, Indonesia
12                                                                  Denpasar, Bali, Nusa Tenggara, Indonesia
13                                                                  Denpasar, Bali, Nusa Tenggara, Indonesia
14
15
16                                                                                 Villa Kaba by Bukit Vista
17                                                                     Amerta Puratangi Villa by Bukit Vista
18
19                            Pura Wates Canggu No.39, Canggu, Kec. Kuta Utara, Kabupaten Badung, Bali 80351
20                                             Ungasan, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia
21                      Jalan Gubug Sari, Kutuh, Kuta Selatan, Badung, Bali, Nusa Tenggara, 80363, Indonesia
22                                                       Kutuh, Kec. Kuta Sel., Kabupaten Badung, Bali 80361
23                                 Sinduadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta, 55284
24                               gupasan, Kec. Gondomanan, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55122
25                                   Jl. Pantai Bingin, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361
26                                                                                        Kauman, Yogyakarta
27                                                 Pecatu, South Kuta, Badung Regency, Bali 80361, Indonesia
28                                     Jalan Anggrek, Jimbaran, Kec. Kuta Sel., Kabupaten Badung, Bali 80361
29                                          Ungasan, Kec. Kuta Sel., Kabupaten Badung, Bali 80361, Indonesia
30                              Jl. Pantai Pererenan Gg. Bima, Pererenan, Mengwi, Badung Regency, Bali 80351
31                                                                               South Kuta, Bali, Indonesia
32                                         Alang Alang Residence Jimbaran, Jimbaran (Bali), Indonesia, 80361
33  Jln Labuhan Sait Br. Dinas Kulat, Pecatu Uluwatu Uluwatu, Pecatu, South Kuta, Badung Regency, Bali 80361
34                                                                      Peliatan, Ubud, Gianyar, Bali. 80571

In [ ]:
price_villa = []  # List untuk menyimpan judul

for page in range(1, 5):  # Mengiterasi melalui 4 halaman
    url = f'https://www.bukitvista.com/property-type/villa/page/{page}'  # Ganti URL dengan URL sebenarnya
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    div_containers = soup.findAll('div', attrs={'class': 'd-flex align-items-center h-100'})

    for container in div_containers:
        price = container.find('li', attrs={"class":'item-price item-price-text'})
        if price:
            price_villa.append(price.text.strip())

# Membuat dataframe dari list judul
df_villa_price = pd.DataFrame({'harga sewa ($ USD)': price_villa})
print('total properties yang didapat : ', len(df_villa_price))
# Menampilkan dataframe
df_villa_price

<ipython-input-13-af1af19f9e96>:7: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  div_containers = soup.findAll('div', attrs={'class': 'd-flex align-items-center h-100'})

total properties yang didapat :  35

                         harga sewa ($ USD)
0                         $258 per 2 nights
1           Starting from USD 161 per night
2                           USD 202 / Night
3        Starting from USD 715 per 2 nights
4            Starting from USD 84 per night
5           Starting from USD 118 per night
6           Starting from USD 165 per night
7           Starting from USD 167 per night
8           Starting from USD 100 per night
9           Starting from USD 108 per night
10          Starting from USD 202 per night
11           Starting from USD 91 per night
12           Starting from USD 89 per night
13           Starting from USD 73 per night
14          Starting from USD 165 per night
15          Starting from USD 172 per night
16       Starting from USD 430 per 2 nights
17        Starting from USD 2,400 per month
18             Start from $72 USD per night
19          Start from $2,200 USD per Month
20        Starting from USD 2,200 per month
21         Starting from USD 1750 per Month
22          Start from $3,200 USD per Month
23  Mulai dari Rp1.930.000 Rupiah per Malam
24  Mulai dari Rp1.750.000 Rupiah per Malam
25          Start from $5,590 USD per Month
26                      Start from $100 USD
27          Start from $4,600 USD per Month
28          Start from $1,780 USD per Month
29          Start from $2,570 USD per Month
30
31            Start from $790 USD per Month
32          Start from $3,350 USD per Month
33          Start from $4,930 USD per Month
34            Start from $890 USD per Month

In [ ]:
bedroom_villa = []  # List untuk menyimpan judul

for page in range(1, 5):  # Mengiterasi melalui 4 halaman
    url = f'https://www.bukitvista.com/property-type/villa/page/{page}'  # Ganti URL dengan URL sebenarnya
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    div_containers = soup.findAll('div', attrs={'class': 'd-flex align-items-center h-100'})

    for container in div_containers:
        bedroom = container.find('li', attrs={"class":'h-beds'})
        #
        if bedroom:
            bedroom_villa.append(bedroom.text.strip())

# Membuat dataframe dari list judul
df_villa_kamar = pd.DataFrame({'kamar': bedroom_villa})
print('total properties yang didapat : ', len(df_villa_kamar))
# Menampilkan dataframe
df_villa_kamar

<ipython-input-15-ed117a44568b>:7: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  div_containers = soup.findAll('div', attrs={'class': 'd-flex align-items-center h-100'})

total properties yang didapat :  35

      kamar
0   Beds: 2
1   Beds: 3
2   Beds: 4
3   Beds: 3
4   Beds: 2
5   Beds: 2
6   Beds: 2
7   Beds: 3
8   Beds: 2
9   Beds: 2
10  Beds: 2
11  Beds: 2
12  Beds: 2
13  Beds: 2
14   Bed: 1
15  Beds: 2
16  Beds: 2
17  Beds: 3
18  Beds: 2
19  Beds: 2
20  Beds: 2
21  Beds: 3
22  Beds: 3
23  Beds: 3
24  Beds: 4
25  Beds: 4
26  Beds: 4
27  Beds: 3
28  Beds: 2
29  Beds: 3
30  Beds: 3
31   Bed: 1
32  Beds: 5
33  Beds: 4
34   Bed: 1

In [ ]:
bathroom_villa = []  # List untuk menyimpan judul

for page in range(1, 5):  # Mengiterasi melalui 4 halaman
    url = f'https://www.bukitvista.com/property-type/villa/page/{page}'  # Ganti URL dengan URL sebenarnya / API method
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    div_containers = soup.findAll('div', attrs={'class': 'd-flex align-items-center h-100'})

    for container in div_containers:
        bathroom = container.find('li', attrs={"class":'h-baths'})
        if bathroom:
            bathroom_villa.append(bathroom.text.strip())

# Membuat dataframe dari list judul
df_villa_kamarmandi = pd.DataFrame({'kamar mandi': bathroom_villa})
print('total properties yang didapat : ', len(df_villa_kamarmandi))
# Menampilkan dataframe
df_villa_kamarmandi.head()

<ipython-input-16-1f836d74e09d>:7: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  div_containers = soup.findAll('div', attrs={'class': 'd-flex align-items-center h-100'})

total properties yang didapat :  35

  kamar mandi
0    Baths: 2
1    Baths: 3
2    Baths: 4
3    Baths: 4
4    Baths: 2

In [ ]:
df_villa = pd.concat([df_villa_title, df_villa_address, df_villa_price, df_villa_kamar, df_villa_kamarmandi], axis=1)
print('total properties yang didapat : ', len(df_villa))
df_villa.head()

total properties yang didapat :  35

,title,alamat,harga sewa ($ USD),kamar,kamar mandi
0,Uluwatu Modern Boho Villa Near Nyang Nyang Beach,"Jl. Batu Nunggul No.1, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",$258 per 2 nights,Beds: 2,Baths: 2
1,Bingin Beach Hideaway: Group Villa with Pool & BBQ,"Jl. Pantai Cemongkak Gg. Samuh Sari No.2, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",Starting from USD 161 per night,Beds: 3,Baths: 3
2,4-Bedroom Mediterranean Luxury Villa with Ubud Rooftop View,"Jl. Suweta, Ubud, Kecamatan Ubud, Kabupaten Gianyar, Bali 80571",USD 202 / Night,Beds: 4,Baths: 4
3,Luxurious 3-Bedroom Nusa Dua Seafront Villa w/ Private Beach,,Starting from USD 715 per 2 nights,Beds: 3,Baths: 4
4,Grand Villa Retreat w/ Pool & Garden in Ungasan,"Jl. Pantai Balangan I No.9x, Ungasan, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",Starting from USD 84 per night,Beds: 2,Baths: 2

# Cleaning to get values -> Tambahan Assignment
Perintah : Jawablah pertanyaan pada keterangan tiap proses berikut
- `clue` docs regex : https://regexr.com/

In [ ]:
df_villa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               35 non-null     object
 1   alamat              35 non-null     object
 2   harga sewa ($ USD)  35 non-null     object
 3   kamar               35 non-null     object
 4   kamar mandi         35 non-null     object
dtypes: object(5)
memory usage: 1.5+ KB

## 1. coba terjemahkan proses `.str.extract(r'(\d+\.?\d*)')` tersebut apa maknanya dan tulis dalam markdown ?

In [ ]:
import re # library regex
# get values in bathroom
df_villa['jumlah_kamar_mandi'] = df_villa['kamar mandi'].str.extract(r'(\d+\.?\d*)')
df_villa

,title,alamat,harga sewa ($ USD),kamar,kamar mandi,jumlah_kamar_mandi
0,Uluwatu Modern Boho Villa Near Nyang Nyang Beach,"Jl. Batu Nunggul No.1, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",$258 per 2 nights,Beds: 2,Baths: 2,2
1,Bingin Beach Hideaway: Group Villa with Pool & BBQ,"Jl. Pantai Cemongkak Gg. Samuh Sari No.2, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",Starting from USD 161 per night,Beds: 3,Baths: 3,3
2,4-Bedroom Mediterranean Luxury Villa with Ubud Rooftop View,"Jl. Suweta, Ubud, Kecamatan Ubud, Kabupaten Gianyar, Bali 80571",USD 202 / Night,Beds: 4,Baths: 4,4
3,Luxurious 3-Bedroom Nusa Dua Seafront Villa w/ Private Beach,,Starting from USD 715 per 2 nights,Beds: 3,Baths: 4,4
4,Grand Villa Retreat w/ Pool & Garden in Ungasan,"Jl. Pantai Balangan I No.9x, Ungasan, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",Starting from USD 84 per night,Beds: 2,Baths: 2,2
5,Surfer’s Villa 4 Mins to Bingin & Dreamland Beach by Bukit Vista,"Pecatu, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia",Starting from USD 118 per night,Beds: 2,Baths: 2.5,2.5
6,Private Pool Villa Minutes from Bingin Surf Haven by Bukit Vista,"Pecatu, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia",Starting from USD 165 per night,Beds: 2,Baths: 2,2
7,Ungasan Exquisite Villa w/ Rooftop & Private Pool by Bukit Vista,"Ungasan, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia",Starting from USD 167 per night,Beds: 3,Baths: 3.5,3.5
8,Sun-Soaked Canggu Villa Perfect for Families,"Tibubeneng, Kuta Utara, Badung, Bali, Nusa Tenggara, Indonesia",Starting from USD 100 per night,Beds: 2,Baths: 2,2
9,Sunny Exquisite Umalas Villa: 20 Minutes to Canggu,,Starting from USD 108 per night,Beds: 2,Baths: 2,2
10,Dazzling Villa with Pool and Rooftop in Bingin,,Starting from USD 202 per night,Beds: 2,Baths: 2,2
11,Sun-Soaked 2BR Villa w/ Pool 15-Min Ride to Beach,"Denpasar, Bali, Nusa Tenggara, Indonesia",Starting from USD 91 per night,Beds: 2,Baths: 2,2
12,Voguish Penthouse with Rooftop Pool Near Canggu,"Denpasar, Bali, Nusa Tenggara, Indonesia",Starting from USD 89 per night,Beds: 2,Baths: 2,2
13,Artisanal Berawa Villa: 11 mins Ride to Beach,"Denpasar, Bali, Nusa Tenggara, Indonesia",Starting from USD 73 per night,Beds: 2,Baths: 2,2
14,Private Ungasan Hideaway Villa with Pool Oasis,,Starting from USD 165 per night,Bed: 1,Bath: 1,1
15,Sunny Tropical Luxe Villa in Ungasan with Pool,,Starting from USD 172 per night,Beds: 2,Baths: 2,2
16,Dreamy Haven w/ Pool | 300m from Bingin Beach,Villa Kaba by Bukit Vista,Starting from USD 430 per 2 nights,Beds: 2,Baths: 2,2
17,Ungasan Haven: 3BR Villa w/ Private Pool Retreat,Amerta Puratangi Villa by Bukit Vista,"Starting from USD 2,400 per month",Beds: 3,Baths: 3.5,3.5
18,Unwind in Tabanan Remote Jungle with Infinity Pool,,Start from $72 USD per night,Beds: 2,Baths: 2,2
19,Villa by Rice Fields in Canggu,"Pura Wates Canggu No.39, Canggu, Kec. Kuta Utara, Kabupaten Badung, Bali 80351","Start from $2,200 USD per Month",Beds: 2,Baths: 2,2
20,Group Getaway: Cozy Villa w/Pool Near GWK Park￼,"Ungasan, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia","Starting from USD 2,200 per month",Beds: 2,Baths: 2.5,2.5
21,Tranquil Kutuh Villa w/ Pool – Ideal for Groups,"Jalan Gubug Sari, Kutuh, Kuta Selatan, Badung, Bali, Nusa Tenggara, 80363, Indonesia",Starting from USD 1750 per Month,Beds: 3,Baths: 3,3
22,Spacious New Tropical Villa w/ GWK View,"Kutuh, Kec. Kuta Sel., Kabupaten Badung, Bali 80361","Start from $3,200 USD per Month",Beds: 3,Baths: 3,3
23,3BR Javanese Traditional Relaxing Villa with Pool,"Sinduadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta, 55284",Mulai dari Rp1.930.000 Rupiah per Malam,Beds: 3,Baths: 2.5,2.5
24,Bukit Vista | Heritage Joglo Villa w/ Private Pool,"gupasan, Kec. Gondomanan, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55122",Mulai dari Rp1.750.000 Rupiah per Malam,Beds: 4,Baths: 3,3
25,Bohemian Beachfront Surf Villa by the Bingin Beach,"Jl. Pantai Bingin, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361","Start from $5,590 USD per Month",Beds: 4,Baths: 3,3
26,Bukit Vista | Heritage Joglo Villa w/ Private Pool,"Kauman, Yogyakarta",Start from $100 USD,Beds: 4,Baths: 3,3
27,Bukit Vista | Stunning 3BR Villa Near Padang Beach,"Pecatu, South Kuta, Badung Regency, Bali 80361, Indonesia","Start from $4,600 USD per Month",Beds: 3,Baths: 3,3
28,Quaint & Homey Balinese Villa w/ Private Pool,"Jalan Anggrek, Jimbaran, Kec. Kuta Sel., Kabupaten Badung, Bali 80361","Start from $1,780 USD per Month",Beds: 2,Baths: 2,2
29,Tranquil 3BR Villa in Jimbaran with Wi-Fi + Pool,"Ungasan, Kec. Kuta Sel., Kabupaten Badung, Bali 80361, Indonesia","Start from $2,570 USD per Month",Beds: 3,Baths: 3,3
30,Lovely Private Pool Villa in Strategic Location,"Jl. Pantai Pererenan Gg. Bima, Pererenan, Mengwi, Badung Regency, Bali 80351",,Beds: 3,Baths: 3,3
31,Authentic Balinese Cabin near Beach | sterilized,"South Kuta, Bali, Indonesia",Start from $790 USD per Month,Bed: 1,Bath: 1,1
32,Family Holiday House w/ Private Pool in Jimbaran,"Alang Alang Residence Jimbaran, Jimbaran (Bali), Indonesia, 80361","Start from $3,350 USD per Month",Beds: 5,Baths: 5,5
33,4BR Homey Villa in Uluwatu | Kitchen + Wifi + Pool by Bukit Vista,"Jln Labuhan Sait Br. Dinas Kulat, Pecatu Uluwatu Uluwatu, Pecatu, South Kuta, Badung Regency, Bali 80361","Start from $4,930 USD per Month",Beds: 4,Baths: 4,4
34,Picturesque Cottage in the Heart of Ubud’s Nature,"Peliatan, Ubud, Gianyar, Bali. 80571",Start from $890 USD per Month,Bed: 1,Bath: 1,1

In [ ]:
df_villa['harga sewa ($ USD)']

0                           $258 per 2 nights
1             Starting from USD 161 per night
2                             USD 202 / Night
3          Starting from USD 715 per 2 nights
4              Starting from USD 84 per night
5             Starting from USD 118 per night
6             Starting from USD 165 per night
7             Starting from USD 167 per night
8             Starting from USD 100 per night
9             Starting from USD 108 per night
10            Starting from USD 202 per night
11             Starting from USD 91 per night
12             Starting from USD 89 per night
13             Starting from USD 73 per night
14            Starting from USD 165 per night
15            Starting from USD 172 per night
16         Starting from USD 430 per 2 nights
17          Starting from USD 2,400 per month
18              Start from $144 USD per night
19            Start from $2,200 USD per Month
20          Starting from USD 2,200 per month
21           Starting from USD 1750 per Month
22            Start from $3,200 USD per Month
23    Mulai dari Rp1.930.000 Rupiah per Malam
24    Mulai dari Rp1.750.000 Rupiah per Malam
25            Start from $5,590 USD per Month
26                        Start from $100 USD
27            Start from $4,600 USD per Month
28            Start from $1,780 USD per Month
29            Start from $2,570 USD per Month
30
31              Start from $790 USD per Month
32            Start from $3,350 USD per Month
33            Start from $4,930 USD per Month
34              Start from $890 USD per Month
Name: harga sewa ($ USD), dtype: object

## 2. Terjemahkan proses yang ada pada code `extract_usd` tersebut apa maknanya dan tulis dalam markdown ?

In [ ]:
# Konversi angka ke satuan USD
import numpy as np

def extract_usd(value):

    # Cek jika dalam USD

    if "USD" in value or "$" in value:

        usd_match = re.search(r'(\d+[\.,]?\d*)', value)

        if usd_match:

            return float(usd_match.group(1).replace(',', ''))

    # Cek jika dalam Rupiah

    elif "Rp" in value:

        rp_match = re.search(r'Rp([\d\.]+)', value)

        if rp_match:

            rupiah = float(rp_match.group(1).replace('.', ''))

            return np.ceil(rupiah / 16380)  # Konversi ke USD dan bulatkan ke atas

    return np.nan  # Jika tidak sesuai format

In [ ]:
# Tambahkan kolom baru untuk nilai USD
# df_villa['harga dalam USD'] = df_villa['harga sewa ($ USD)'].apply(extract_usd)
# atau memakai lambda
df_villa['harga dalam USD'] = df_villa['harga sewa ($ USD)'].apply(lambda x: extract_usd(x))
df_villa

,title,alamat,harga sewa ($ USD),kamar,kamar mandi,jumlah_kamar_mandi,harga dalam USD
0,Uluwatu Modern Boho Villa Near Nyang Nyang Beach,"Jl. Batu Nunggul No.1, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",$258 per 2 nights,Beds: 2,Baths: 2,2,258.0
1,Bingin Beach Hideaway: Group Villa with Pool & BBQ,"Jl. Pantai Cemongkak Gg. Samuh Sari No.2, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",Starting from USD 161 per night,Beds: 3,Baths: 3,3,161.0
2,4-Bedroom Mediterranean Luxury Villa with Ubud Rooftop View,"Jl. Suweta, Ubud, Kecamatan Ubud, Kabupaten Gianyar, Bali 80571",USD 202 / Night,Beds: 4,Baths: 4,4,202.0
3,Luxurious 3-Bedroom Nusa Dua Seafront Villa w/ Private Beach,,Starting from USD 715 per 2 nights,Beds: 3,Baths: 4,4,715.0
4,Grand Villa Retreat w/ Pool & Garden in Ungasan,"Jl. Pantai Balangan I No.9x, Ungasan, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",Starting from USD 84 per night,Beds: 2,Baths: 2,2,84.0
5,Surfer’s Villa 4 Mins to Bingin & Dreamland Beach by Bukit Vista,"Pecatu, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia",Starting from USD 118 per night,Beds: 2,Baths: 2.5,2.5,118.0
6,Private Pool Villa Minutes from Bingin Surf Haven by Bukit Vista,"Pecatu, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia",Starting from USD 165 per night,Beds: 2,Baths: 2,2,165.0
7,Ungasan Exquisite Villa w/ Rooftop & Private Pool by Bukit Vista,"Ungasan, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia",Starting from USD 167 per night,Beds: 3,Baths: 3.5,3.5,167.0
8,Sun-Soaked Canggu Villa Perfect for Families,"Tibubeneng, Kuta Utara, Badung, Bali, Nusa Tenggara, Indonesia",Starting from USD 100 per night,Beds: 2,Baths: 2,2,100.0
9,Sunny Exquisite Umalas Villa: 20 Minutes to Canggu,,Starting from USD 108 per night,Beds: 2,Baths: 2,2,108.0
10,Dazzling Villa with Pool and Rooftop in Bingin,,Starting from USD 202 per night,Beds: 2,Baths: 2,2,202.0
11,Sun-Soaked 2BR Villa w/ Pool 15-Min Ride to Beach,"Denpasar, Bali, Nusa Tenggara, Indonesia",Starting from USD 91 per night,Beds: 2,Baths: 2,2,91.0
12,Voguish Penthouse with Rooftop Pool Near Canggu,"Denpasar, Bali, Nusa Tenggara, Indonesia",Starting from USD 89 per night,Beds: 2,Baths: 2,2,89.0
13,Artisanal Berawa Villa: 11 mins Ride to Beach,"Denpasar, Bali, Nusa Tenggara, Indonesia",Starting from USD 73 per night,Beds: 2,Baths: 2,2,73.0
14,Private Ungasan Hideaway Villa with Pool Oasis,,Starting from USD 165 per night,Bed: 1,Bath: 1,1,165.0
15,Sunny Tropical Luxe Villa in Ungasan with Pool,,Starting from USD 172 per night,Beds: 2,Baths: 2,2,172.0
16,Dreamy Haven w/ Pool | 300m from Bingin Beach,Villa Kaba by Bukit Vista,Starting from USD 430 per 2 nights,Beds: 2,Baths: 2,2,430.0
17,Ungasan Haven: 3BR Villa w/ Private Pool Retreat,Amerta Puratangi Villa by Bukit Vista,"Starting from USD 2,400 per month",Beds: 3,Baths: 3.5,3.5,2400.0
18,Unwind in Tabanan Remote Jungle with Infinity Pool,,Start from $72 USD per night,Beds: 2,Baths: 2,2,72.0
19,Villa by Rice Fields in Canggu,"Pura Wates Canggu No.39, Canggu, Kec. Kuta Utara, Kabupaten Badung, Bali 80351","Start from $2,200 USD per Month",Beds: 2,Baths: 2,2,2200.0
20,Group Getaway: Cozy Villa w/Pool Near GWK Park￼,"Ungasan, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia","Starting from USD 2,200 per month",Beds: 2,Baths: 2.5,2.5,2200.0
21,Tranquil Kutuh Villa w/ Pool – Ideal for Groups,"Jalan Gubug Sari, Kutuh, Kuta Selatan, Badung, Bali, Nusa Tenggara, 80363, Indonesia",Starting from USD 1750 per Month,Beds: 3,Baths: 3,3,1750.0
22,Spacious New Tropical Villa w/ GWK View,"Kutuh, Kec. Kuta Sel., Kabupaten Badung, Bali 80361","Start from $3,200 USD per Month",Beds: 3,Baths: 3,3,3200.0
23,3BR Javanese Traditional Relaxing Villa with Pool,"Sinduadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta, 55284",Mulai dari Rp1.930.000 Rupiah per Malam,Beds: 3,Baths: 2.5,2.5,118.0
24,Bukit Vista | Heritage Joglo Villa w/ Private Pool,"gupasan, Kec. Gondomanan, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55122",Mulai dari Rp1.750.000 Rupiah per Malam,Beds: 4,Baths: 3,3,107.0
25,Bohemian Beachfront Surf Villa by the Bingin Beach,"Jl. Pantai Bingin, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361","Start from $5,590 USD per Month",Beds: 4,Baths: 3,3,5590.0
26,Bukit Vista | Heritage Joglo Villa w/ Private Pool,"Kauman, Yogyakarta",Start from $100 USD,Beds: 4,Baths: 3,3,100.0
27,Bukit Vista | Stunning 3BR Villa Near Padang Beach,"Pecatu, South Kuta, Badung Regency, Bali 80361, Indonesia","Start from $4,600 USD per Month",Beds: 3,Baths: 3,3,4600.0
28,Quaint & Homey Balinese Villa w/ Private Pool,"Jalan Anggrek, Jimbaran, Kec. Kuta Sel., Kabupaten Badung, Bali 80361","Start from $1,780 USD per Month",Beds: 2,Baths: 2,2,1780.0
29,Tranquil 3BR Villa in Jimbaran with Wi-Fi + Pool,"Ungasan, Kec. Kuta Sel., Kabupaten Badung, Bali 80361, Indonesia","Start from $2,570 USD per Month",Beds: 3,Baths: 3,3,2570.0
30,Lovely Private Pool Villa in Strategic Location,"Jl. Pantai Pererenan Gg. Bima, Pererenan, Mengwi, Badung Regency, Bali 80351",,Beds: 3,Baths: 3,3,NaN
31,Authentic Balinese Cabin near Beach | sterilized,"South Kuta, Bali, Indonesia",Start from $790 USD per Month,Bed: 1,Bath: 1,1,790.0
32,Family Holiday House w/ Private Pool in Jimbaran,"Alang Alang Residence Jimbaran, Jimbaran (Bali), Indonesia, 80361","Start from $3,350 USD per Month",Beds: 5,Baths: 5,5,3350.0
33,4BR Homey Villa in Uluwatu | Kitchen + Wifi + Pool by Bukit Vista,"Jln Labuhan Sait Br. Dinas Kulat, Pecatu Uluwatu Uluwatu, Pecatu, South Kuta, Badung Regency, Bali 80361","Start from $4,930 USD per Month",Beds: 4,Baths: 4,4,4930.0
34,Picturesque Cottage in the Heart of Ubud’s Nature,"Peliatan, Ubud, Gianyar, Bali. 80571",Start from $890 USD per Month,Bed: 1,Bath: 1,1,890.0

## 3. Terjemahkan proses code `.str.extract(r'per (.+)$')` tersebut apa maknanya dan tulis dalam markdown ?

In [ ]:
# Ekstraksi kata-kata setelah 'per'
df_villa['periode'] = df_villa['harga sewa ($ USD)'].str.extract(r'per (.+)$')
df_villa

,title,alamat,harga sewa ($ USD),kamar,kamar mandi,jumlah_kamar_mandi,harga dalam USD,periode
0,Uluwatu Modern Boho Villa Near Nyang Nyang Beach,"Jl. Batu Nunggul No.1, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",$258 per 2 nights,Beds: 2,Baths: 2,2,258.0,2 nights
1,Bingin Beach Hideaway: Group Villa with Pool & BBQ,"Jl. Pantai Cemongkak Gg. Samuh Sari No.2, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",Starting from USD 161 per night,Beds: 3,Baths: 3,3,161.0,night
2,4-Bedroom Mediterranean Luxury Villa with Ubud Rooftop View,"Jl. Suweta, Ubud, Kecamatan Ubud, Kabupaten Gianyar, Bali 80571",USD 202 / Night,Beds: 4,Baths: 4,4,202.0,NaN
3,Luxurious 3-Bedroom Nusa Dua Seafront Villa w/ Private Beach,,Starting from USD 715 per 2 nights,Beds: 3,Baths: 4,4,715.0,2 nights
4,Grand Villa Retreat w/ Pool & Garden in Ungasan,"Jl. Pantai Balangan I No.9x, Ungasan, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",Starting from USD 84 per night,Beds: 2,Baths: 2,2,84.0,night
5,Surfer’s Villa 4 Mins to Bingin & Dreamland Beach by Bukit Vista,"Pecatu, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia",Starting from USD 118 per night,Beds: 2,Baths: 2.5,2.5,118.0,night
6,Private Pool Villa Minutes from Bingin Surf Haven by Bukit Vista,"Pecatu, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia",Starting from USD 165 per night,Beds: 2,Baths: 2,2,165.0,night
7,Ungasan Exquisite Villa w/ Rooftop & Private Pool by Bukit Vista,"Ungasan, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia",Starting from USD 167 per night,Beds: 3,Baths: 3.5,3.5,167.0,night
8,Sun-Soaked Canggu Villa Perfect for Families,"Tibubeneng, Kuta Utara, Badung, Bali, Nusa Tenggara, Indonesia",Starting from USD 100 per night,Beds: 2,Baths: 2,2,100.0,night
9,Sunny Exquisite Umalas Villa: 20 Minutes to Canggu,,Starting from USD 108 per night,Beds: 2,Baths: 2,2,108.0,night
10,Dazzling Villa with Pool and Rooftop in Bingin,,Starting from USD 202 per night,Beds: 2,Baths: 2,2,202.0,night
11,Sun-Soaked 2BR Villa w/ Pool 15-Min Ride to Beach,"Denpasar, Bali, Nusa Tenggara, Indonesia",Starting from USD 91 per night,Beds: 2,Baths: 2,2,91.0,night
12,Voguish Penthouse with Rooftop Pool Near Canggu,"Denpasar, Bali, Nusa Tenggara, Indonesia",Starting from USD 89 per night,Beds: 2,Baths: 2,2,89.0,night
13,Artisanal Berawa Villa: 11 mins Ride to Beach,"Denpasar, Bali, Nusa Tenggara, Indonesia",Starting from USD 73 per night,Beds: 2,Baths: 2,2,73.0,night
14,Private Ungasan Hideaway Villa with Pool Oasis,,Starting from USD 165 per night,Bed: 1,Bath: 1,1,165.0,night
15,Sunny Tropical Luxe Villa in Ungasan with Pool,,Starting from USD 172 per night,Beds: 2,Baths: 2,2,172.0,night
16,Dreamy Haven w/ Pool | 300m from Bingin Beach,Villa Kaba by Bukit Vista,Starting from USD 430 per 2 nights,Beds: 2,Baths: 2,2,430.0,2 nights
17,Ungasan Haven: 3BR Villa w/ Private Pool Retreat,Amerta Puratangi Villa by Bukit Vista,"Starting from USD 2,400 per month",Beds: 3,Baths: 3.5,3.5,2400.0,month
18,Unwind in Tabanan Remote Jungle with Infinity Pool,,Start from $72 USD per night,Beds: 2,Baths: 2,2,72.0,night
19,Villa by Rice Fields in Canggu,"Pura Wates Canggu No.39, Canggu, Kec. Kuta Utara, Kabupaten Badung, Bali 80351","Start from $2,200 USD per Month",Beds: 2,Baths: 2,2,2200.0,Month
20,Group Getaway: Cozy Villa w/Pool Near GWK Park￼,"Ungasan, Kuta Selatan, Badung, Bali, Nusa Tenggara, Indonesia","Starting from USD 2,200 per month",Beds: 2,Baths: 2.5,2.5,2200.0,month
21,Tranquil Kutuh Villa w/ Pool – Ideal for Groups,"Jalan Gubug Sari, Kutuh, Kuta Selatan, Badung, Bali, Nusa Tenggara, 80363, Indonesia",Starting from USD 1750 per Month,Beds: 3,Baths: 3,3,1750.0,Month
22,Spacious New Tropical Villa w/ GWK View,"Kutuh, Kec. Kuta Sel., Kabupaten Badung, Bali 80361","Start from $3,200 USD per Month",Beds: 3,Baths: 3,3,3200.0,Month
23,3BR Javanese Traditional Relaxing Villa with Pool,"Sinduadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta, 55284",Mulai dari Rp1.930.000 Rupiah per Malam,Beds: 3,Baths: 2.5,2.5,118.0,Malam
24,Bukit Vista | Heritage Joglo Villa w/ Private Pool,"gupasan, Kec. Gondomanan, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55122",Mulai dari Rp1.750.000 Rupiah per Malam,Beds: 4,Baths: 3,3,107.0,Malam
25,Bohemian Beachfront Surf Villa by the Bingin Beach,"Jl. Pantai Bingin, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361","Start from $5,590 USD per Month",Beds: 4,Baths: 3,3,5590.0,Month
26,Bukit Vista | Heritage Joglo Villa w/ Private Pool,"Kauman, Yogyakarta",Start from $100 USD,Beds: 4,Baths: 3,3,100.0,NaN
27,Bukit Vista | Stunning 3BR Villa Near Padang Beach,"Pecatu, South Kuta, Badung Regency, Bali 80361, Indonesia","Start from $4,600 USD per Month",Beds: 3,Baths: 3,3,4600.0,Month
28,Quaint & Homey Balinese Villa w/ Private Pool,"Jalan Anggrek, Jimbaran, Kec. Kuta Sel., Kabupaten Badung, Bali 80361","Start from $1,780 USD per Month",Beds: 2,Baths: 2,2,1780.0,Month
29,Tranquil 3BR Villa in Jimbaran with Wi-Fi + Pool,"Ungasan, Kec. Kuta Sel., Kabupaten Badung, Bali 80361, Indonesia","Start from $2,570 USD per Month",Beds: 3,Baths: 3,3,2570.0,Month
30,Lovely Private Pool Villa in Strategic Location,"Jl. Pantai Pererenan Gg. Bima, Pererenan, Mengwi, Badung Regency, Bali 80351",,Beds: 3,Baths: 3,3,NaN,NaN
31,Authentic Balinese Cabin near Beach | sterilized,"South Kuta, Bali, Indonesia",Start from $790 USD per Month,Bed: 1,Bath: 1,1,790.0,Month
32,Family Holiday House w/ Private Pool in Jimbaran,"Alang Alang Residence Jimbaran, Jimbaran (Bali), Indonesia, 80361","Start from $3,350 USD per Month",Beds: 5,Baths: 5,5,3350.0,Month
33,4BR Homey Villa in Uluwatu | Kitchen + Wifi + Pool by Bukit Vista,"Jln Labuhan Sait Br. Dinas Kulat, Pecatu Uluwatu Uluwatu, Pecatu, South Kuta, Badung Regency, Bali 80361","Start from $4,930 USD per Month",Beds: 4,Baths: 4,4,4930.0,Month
34,Picturesque Cottage in the Heart of Ubud’s Nature,"Peliatan, Ubud, Gianyar, Bali. 80571",Start from $890 USD per Month,Bed: 1,Bath: 1,1,890.0,Month

In [ ]:
df_villa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               35 non-null     object
 1   alamat              35 non-null     object
 2   harga sewa ($ USD)  35 non-null     object
 3   kamar               35 non-null     object
 4   kamar mandi         35 non-null     object
 5   jumlah_kamar_mandi  35 non-null     object
 6   harga dalam USD     34 non-null     float64
 7   periode             32 non-null     object
dtypes: float64(1), object(7)
memory usage: 2.3+ KB

## 4. Jelaskan apa makna proses code pada function `convert_to_float` tulis dalam markdown ?

In [ ]:
# Konversi kolom 'kamar' dan 'jumlah_kamar_mandi' ke float

def convert_to_float(value):

    try:

        return float(value)

    except ValueError:

        return np.nan  # Jika tidak dapat dikonversi, isi dengan NaN



df_villa['kamar'] = df_villa['kamar'].apply(convert_to_float)

df_villa['jumlah_kamar_mandi'] = df_villa['jumlah_kamar_mandi'].apply(convert_to_float)
df_villa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               35 non-null     object
 1   alamat              35 non-null     object
 2   harga sewa ($ USD)  35 non-null     object
 3   kamar               35 non-null     float64
 4   kamar mandi         35 non-null     object
 5   jumlah_kamar_mandi  35 non-null     float64
 6   harga dalam USD     34 non-null     float64
 7   periode             32 non-null     object
dtypes: float64(3), object(5)
memory usage: 2.3+ KB

In [ ]:
df_villa.head()

,title,alamat,harga sewa ($ USD),kamar,kamar mandi,jumlah_kamar_mandi,harga dalam USD,periode
0,Uluwatu Modern Boho Villa Near Nyang Nyang Beach,"Jl. Batu Nunggul No.1, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",$258 per 2 nights,2.0,Baths: 2,2.0,258.0,2 nights
1,Bingin Beach Hideaway: Group Villa with Pool & BBQ,"Jl. Pantai Cemongkak Gg. Samuh Sari No.2, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",Starting from USD 161 per night,3.0,Baths: 3,3.0,161.0,night
2,4-Bedroom Mediterranean Luxury Villa with Ubud Rooftop View,"Jl. Suweta, Ubud, Kecamatan Ubud, Kabupaten Gianyar, Bali 80571",USD 202 / Night,4.0,Baths: 4,4.0,202.0,NaN
3,Luxurious 3-Bedroom Nusa Dua Seafront Villa w/ Private Beach,,Starting from USD 715 per 2 nights,3.0,Baths: 4,4.0,715.0,2 nights
4,Grand Villa Retreat w/ Pool & Garden in Ungasan,"Jl. Pantai Balangan I No.9x, Ungasan, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",Starting from USD 84 per night,2.0,Baths: 2,2.0,84.0,night