In [60]:
# import library yang dibutuhkan
import requests
from bs4 import BeautifulSoup
import time
from selenium import webdriver
import pandas as pd
from selenium.webdriver.support.ui import WebDriverWait   # ambil html yg mana, tagar yang mana
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import os
pd.options.display.max_colwidth = 300
import re

In [33]:
url = "https://ubuvilla.com/property?page=1"
driver = webdriver.Firefox()
driver.get(url)

soup = BeautifulSoup(driver.page_source, "html.parser")

In [34]:
driver

In [35]:
print(soup)

<html class="js flexbox canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients no-cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths" lang="en-US" style=""><head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="telephone=no" name="format-detection"/>
<title>Ubu Villa – Best Thematic Villa</title>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<link href="https://ubuvilla.com/assets/css/bootstrap.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/bootstrap-theme.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/bootstrap-slider.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/chosen.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/style.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/wp-rem-plugin.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/responsive.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/daterangepicker.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/color.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/iconmoon.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/prettyPhoto.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/swiper.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/croppic.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/style-animate.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/flexslider.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/css/widget.css" rel="stylesheet" type="text/css"/>
<link href="https://ubuvilla.com/assets/images/favicon.png" rel="icon" type="image/png"/>
<!--<link rel="stylesheet" href="https://ubuvilla.com/assets/font-awesome/4.7.0/css/font-awesome.min.css">-->
<!--icon tiktok-->
<!--<link rel="stylesheet" href="https://ubuvilla.com/assets/font-awesome/5.15.3/css/all.min.css" />-->
<img alt="" src="//stats.symptoma.com/matomo.php?idsite=1&amp;rec=1&amp;action_name=Chatbot&amp;url=https://www.symptoma.com/chatbot&amp;urlref=" style="border: 0px;"/><script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-400239261&amp;cx=c&amp;gtm=45je55s2h1v894377579za200&amp;tag_exp=101509157~103116026~103200004~103233427~103252644~103252646~103351866~103351868~104481633~104481635~104559073~104559075~104612245~104612247" type="text/javascript"></script><script async="" src="https://live.aksoro.co.id/widget.js" type="text/javascript"></script><script async="" src="https://connect.facebook.net/signals/config/1151614612371458?v=2.9.203&amp;r=stable&amp;domain=ubuvilla.com&amp;hme=36c7454c4b078660353e5d4c89e3eaca439a56e5c3ceaadddff6c79ae427835a&amp;ex_m=74%2C128%2C113%2C117%2C65%2C6%2C106%2C73%2C19%2C101%2C93%2C55%2C58%2C183%2C204%2C211%2C207%2C208%2C210%2C32%2C107%2C57%2C81%2C209%2C178%2C181%2C205%2C206%2C191%2C140%2C45%2C196%2C193%2C194%2C37%2C152%2C18%2C54%2C200%2C199%2C142%2C21%2C44%2C2%2C47%2C69%2C70%2C71%2C75%2C97%2C20%2C17%2C100%2C96%2C95%2C114%2C56%2C116%2C42%2C115%2C33%2C98%2C43%2C90%2C29%2C179%2C182%2C149%2C14%2C15%2C16%2C8%2C9%2C28%2C25%2C26%2C61%2C66%2C68%2C79%2C105%2C108%2C30%2C80%2C12%2C10%2C84%2C52%2C24%2C110%2C109%2C111%2C102%2C13%2C23%2C4%2C41%2C78%2C22%2C161%2C136%2C77%2C1%2C99%2C60%2C88%2C36%2C31%2C86%2C87%2C92%2C40%2C7%2C94%2C85%2C48%2C35%2C38%2C0%2C72%2C118%2C91%2C5%2C51%2C50%2C89%2C248%2C176%2C126%2C164%2C157%2C3%2C39%2C67%2C46%2C112%2C49%2C83%2C64%2C63%2C34%2C103%2C62%2C59%2C53%2C82%2C76%2C27%2C104%2C11%2C119"></script><script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-NGCJN78"></script><script src="https://ubuvilla.com/assets/js/jquery.js" type="text/javascript"></script>
<script src="https://ubuvilla.com/assets/js/modernizr.js" type="text/javascript"></script>
<script src="https://ubuvilla.com/assets/js/bootstrap.min.js" type="text/javascript"></script>
<!-- SWEETALERT -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.all.min.js"></script><style type="text/css">html.swal2-shown:not(.swal2-no-backdrop):not(.swal2-toast-shown),
body.swal2-shown:not(.swal2-no-backdrop):not(.swal2-toast-shown) {
  overflow-y: hidden; }

body.swal2-toast-shown.swal2-has-input > .swal2-container > .swal2-toast {
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
      -ms-flex-direction: column;
          flex-direction: column; }
  body.swal2-toast-shown.swal2-has-input > .swal2-container > .swal2-toast .swal2-icon {
    margin: 0 0 15px; }
  body.swal2-toast-shown.swal2-has-input > .swal2-container > .swal2-toast .swal2-buttonswrapper {
    -webkit-box-flex: 1;
        -ms-flex: 1;
            flex: 1;
    -ms-flex-item-align: stretch;
        align-self: stretch;
    -webkit-box-pack: end;
        -ms-flex-pack: end;
            justify-content: flex-end; }
  body.swal2-toast-shown.swal2-has-input > .swal2-container > .swal2-toast .swal2-loading {
    -webkit-box-pack: center;
        -ms-flex-pack: center;
            justify-content: center; }
  body.swal2-toast-shown.swal2-has-input > .swal2-container > .swal2-toast .swal2-input {
    height: 32px;
    font-size: 14px;
    margin: 5px auto; }

body.swal2-toast-shown > .swal2-container {
  position: fixed;
  background-color: transparent; }
  body.swal2-toast-shown > .swal2-container.swal2-shown {
    background-color: transparent; }
  body.swal2-toast-shown > .swal2-container.swal2-top {
    top: 0;
    left: 50%;
    bottom: auto;
    right: auto;
    -webkit-transform: translateX(-50%);
            transform: translateX(-50%); }
  body.swal2-toast-shown > .swal2-container.swal2-top-end, body.swal2-toast-shown > .swal2-container.swal2-top-right {
    top: 0;
    left: auto;
    bottom: auto;
    right: 0; }
  body.swal2-toast-shown > .swal2-container.swal2-top-start, body.swal2-toast-shown > .swal2-container.swal2-top-left {
    top: 0;
    left: 0;
    bottom: auto;
    right: auto; }
  body.swal2-toast-shown > .swal2-container.swal2-center-start, body.swal2-toast-shown > .swal2-container.swal2-center-left {
    top: 50%;
    left: 0;
    bottom: auto;
    right: auto;
    -webkit-transform: translateY(-50%);
            transform: translateY(-50%); }
  body.swal2-toast-shown > .swal2-container.swal2-center {
    top: 50%;
    left: 50%;
    bottom: auto;
    right: auto;
    -webkit-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%); }
  body.swal2-toast-shown > .swal2-container.swal2-center-end, body.swal2-toast-shown > .swal2-container.swal2-center-right {
    top: 50%;
    left: auto;
    bottom: auto;
    right: 0;
    -webkit-transform: translateY(-50%);
            transform: translateY(-50%); }
  body.swal2-toast-shown > .swal2-container.swal2-bottom-start, body.swal2-toast-shown > .swal2-container.swal2-bottom-left {
    top: auto;
    left: 0;
    bottom: 0;
    right: auto; }
  body.swal2-toast-shown > .swal2-container.swal2-bottom {
    top: auto;
    left: 50%;
    bottom: 0;
    right: auto;
    -webkit-transform: translateX(-50%);
            transform: translateX(-50%); }
  body.swal2-toast-shown > .swal2-container.swal2-bottom-end, body.swal2-toast-shown > .swal2-container.swal2-bottom-right {
    top: auto;
    left: auto;
    bottom: 0;
    right: 0; }

body.swal2-iosfix {
  position: fixed;
  left: 0;
  right: 0; }

body.swal2-no-backdrop > .swal2-shown {
  top: auto;
  bottom: auto;
  left: auto;
  right: auto;
  background-color: transparent; }
  body.swal2-no-backdrop > .swal2-shown > .swal2-modal {
    -webkit-box-shadow: 0 0 10px rgba(0, 0, 0, 0.4);
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.4); }
  body.swal2-no-backdrop > .swal2-shown.swal2-top {
    top: 0;
    left: 50%;
    -webkit-transform: translateX(-50%);
            transform: translateX(-50%); }
  body.swal2-no-backdrop > .swal2-shown.swal2-top-start, body.swal2-no-backdrop > .swal2-shown.swal2-top-left {
    top: 0;
    left: 0; }
  body.swal2-no-backdrop > .swal2-shown.swal2-top-end, body.swal2-no-backdrop > .swal2-shown.swal2-top-right {
    top: 0;
    right: 0; }
  body.swal2-no-backdrop > .swal2-shown.swal2-center {
    top: 50%;
    left: 50%;
    -webkit-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%); }
  body.swal2-no-backdrop > .swal2-shown.swal2-center-start, body.swal2-no-backdrop > .swal2-shown.swal2-center-left {
    top: 50%;
    left: 0;
    -webkit-transform: translateY(-50%);
            transform: translateY(-50%); }
  body.swal2-no-backdrop > .swal2-shown.swal2-center-end, body.swal2-no-backdrop > .swal2-shown.swal2-center-right {
    top: 50%;
    right: 0;
    -webkit-transform: translateY(-50%);
            transform: translateY(-50%); }
  body.swal2-no-backdrop > .swal2-shown.swal2-bottom {
    bottom: 0;
    left: 50%;
    -webkit-transform: translateX(-50%);
            transform: translateX(-50%); }
  body.swal2-no-backdrop > .swal2-shown.swal2-bottom-start, body.swal2-no-backdrop > .swal2-shown.swal2-bottom-left {
    bottom: 0;
    left: 0; }
  body.swal2-no-backdrop > .swal2-shown.swal2-bottom-end, body.swal2-no-backdrop > .swal2-shown.swal2-bottom-right {
    bottom: 0;
    right: 0; }

.swal2-container {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: horizontal;
  -webkit-box-direction: normal;
      -ms-flex-direction: row;
          flex-direction: row;
  -webkit-box-align: center;
      -ms-flex-align: center;
          align-items: center;
  -webkit-box-pack: center;
      -ms-flex-pack: center;
          justify-content: center;
  position: fixed;
  padding: 10px;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: transparent;
  z-index: 1060; }
  .swal2-container.swal2-top {
    -webkit-box-align: start;
        -ms-flex-align: start;
            align-items: flex-start; }
  .swal2-container.swal2-top-start, .swal2-container.swal2-top-left {
    -webkit-box-align: start;
        -ms-flex-align: start;
            align-items: flex-start;
    -webkit-box-pack: start;
        -ms-flex-pack: start;
            justify-content: flex-start; }
  .swal2-container.swal2-top-end, .swal2-container.swal2-top-right {
    -webkit-box-align: start;
        -ms-flex-align: start;
            align-items: flex-start;
    -webkit-box-pack: end;
        -ms-flex-pack: end;
            justify-content: flex-end; }
  .swal2-container.swal2-center {
    -webkit-box-align: center;
        -ms-flex-align: center;
            align-items: center; }
  .swal2-container.swal2-center-start, .swal2-container.swal2-center-left {
    -webkit-box-align: center;
        -ms-flex-align: center;
            align-items: center;
    -webkit-box-pack: start;
        -ms-flex-pack: start;
            justify-content: flex-start; }
  .swal2-container.swal2-center-end, .swal2-container.swal2-center-right {
    -webkit-box-align: center;
        -ms-flex-align: center;
            align-items: center;
    -webkit-box-pack: end;
        -ms-flex-pack: end;
            justify-content: flex-end; }
  .swal2-container.swal2-bottom {
    -webkit-box-align: end;
        -ms-flex-align: end;
            align-items: flex-end; }
  .swal2-container.swal2-bottom-start, .swal2-container.swal2-bottom-left {
    -webkit-box-align: end;
        -ms-flex-align: end;
            align-items: flex-end;
    -webkit-box-pack: start;
        -ms-flex-pack: start;
            justify-content: flex-start; }
  .swal2-container.swal2-bottom-end, .swal2-container.swal2-bottom-right {
    -webkit-box-align: end;
        -ms-flex-align: end;
            align-items: flex-end;
    -webkit-box-pack: end;
        -ms-flex-pack: end;
            justify-content: flex-end; }
  .swal2-container.swal2-grow-fullscreen > .swal2-modal {
    display: -webkit-box !important;
    display: -ms-flexbox !important;
    display: flex !important;
    -webkit-box-flex: 1;
        -ms-flex: 1;
            flex: 1;
    -ms-flex-item-align: stretch;
        align-self: stretch;
    -webkit-box-pack: center;
        -ms-flex-pack: center;
            justify-content: center; }
  .swal2-container.swal2-grow-row > .swal2-modal {
    display: -webkit-box !important;
    display: -ms-flexbox !important;
    display: flex !important;
    -webkit-box-flex: 1;
        -ms-flex: 1;
            flex: 1;
    -ms-flex-line-pack: center;
        align-content: center;
    -webkit-box-pack: center;
        -ms-flex-pack: center;
            justify-content: center; }
  .swal2-container.swal2-grow-column {
    -webkit-box-flex: 1;
        -ms-flex: 1;
            flex: 1;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
        -ms-flex-direction: column;
            flex-direction: column; }
    .swal2-container.swal2-grow-column.swal2-top, .swal2-container.swal2-grow-column.swal2-center, .swal2-container.swal2-grow-column.swal2-bottom {
      -webkit-box-align: center;
          -ms-flex-align: center;
              align-items: center; }
    .swal2-container.swal2-grow-column.swal2-top-start, .swal2-container.swal2-grow-column.swal2-center-start, .swal2-container.swal2-grow-column.swal2-bottom-start, .swal2-container.swal2-grow-column.swal2-top-left, .swal2-container.swal2-grow-column.swal2-center-left, .swal2-container.swal2-grow-column.swal2-bottom-left {
      -webkit-box-align: start;
          -ms-flex-align: start;
              align-items: flex-start; }
    .swal2-container.swal2-grow-column.swal2-top-end, .swal2-container.swal2-grow-column.swal2-center-end, .swal2-container.swal2-grow-column.swal2-bottom-end, .swal2-container.swal2-grow-column.swal2-top-right, .swal2-container.swal2-grow-column.swal2-center-right, .swal2-container.swal2-grow-column.swal2-bottom-right {
      -webkit-box-align: end;
          -ms-flex-align: end;
              align-items: flex-end; }
    .swal2-container.swal2-grow-column > .swal2-modal {
      display: -webkit-box !important;
      display: -ms-flexbox !important;
      display: flex !important;
      -webkit-box-flex: 1;
          -ms-flex: 1;
              flex: 1;
      -ms-flex-line-pack: center;
          align-content: center;
      -webkit-box-pack: center;
          -ms-flex-pack: center;
              justify-content: center; }
  .swal2-container:not(.swal2-top):not(.swal2-top-start):not(.swal2-top-end):not(.swal2-top-left):not(.swal2-top-right):not(.swal2-center-start):not(.swal2-center-end):not(.swal2-center-left):not(.swal2-center-right):not(.swal2-bottom):not(.swal2-bottom-start):not(.swal2-bottom-end):not(.swal2-bottom-left):not(.swal2-bottom-right) > .swal2-modal {
    margin: auto; }
  @media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
    .swal2-container .swal2-modal {
      margin: 0 !important; } }
  .swal2-container.swal2-fade {
    -webkit-transition: background-color .1s;
    transition: background-color .1s; }
  .swal2-container.swal2-shown {
    background-color: rgba(0, 0, 0, 0.4); }

.swal2-popup {
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
      -ms-flex-direction: column;
          flex-direction: column;
  background-color: #fff;
  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
  border-radius: 5px;
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
  text-align: center;
  overflow-x: hidden;
  overflow-y: auto;
  display: none;
  position: relative;
  max-width: 100%; }
  .swal2-popup.swal2-toast {
    width: 300px;
    padding: 0 15px;
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
        -ms-flex-direction: row;
            flex-direction: row;
    -webkit-box-align: center;
        -ms-flex-align: center;
            align-items: center;
    overflow-y: hidden;
    -webkit-box-shadow: 0 0 10px #d9d9d9;
            box-shadow: 0 0 10px #d9d9d9; }
    .swal2-popup.swal2-toast .swal2-title {
      max-width: 300px;
      font-size: 16px;
      text-align: left; }
    .swal2-popup.swal2-toast .swal2-content {
      font-size: 14px;
      text-align: left; }
    .swal2-popup.swal2-toast .swal2-icon {
      width: 32px;
      min-width: 32px;
      height: 32px;
      margin: 0 15px 0 0; }
      .swal2-popup.swal2-toast .swal2-icon.swal2-success .swal2-success-ring {
        width: 32px;
        height: 32px; }
      .swal2-popup.swal2-toast .swal2-icon.swal2-info, .swal2-popup.swal2-toast .swal2-icon.swal2-warning, .swal2-popup.swal2-toast .swal2-icon.swal2-question {
        font-size: 26px;
        line-height: 32px; }
      .swal2-popup.swal2-toast .swal2-icon.swal2-error [class^='swal2-x-mark-line'] {
        top: 14px;
        width: 22px; }
        .swal2-popup.swal2-toast .swal2-icon.swal2-error [class^='swal2-x-mark-line'][class$='left'] {
          left: 5px; }
        .swal2-popup.swal2-toast .swal2-icon.swal2-error [class^='swal2-x-mark-line'][class$='right'] {
          right: 5px; }
    .swal2-popup.swal2-toast .swal2-buttonswrapper {
      margin: 0 0 0 5px; }
    .swal2-popup.swal2-toast .swal2-styled {
      margin: 0 0 0 5px;
      padding: 5px 10px; }
      .swal2-popup.swal2-toast .swal2-styled:focus {
        -webkit-box-shadow: 0 0 0 1px #fff, 0 0 0 2px rgba(50, 100, 150, 0.4);
                box-shadow: 0 0 0 1px #fff, 0 0 0 2px rgba(50, 100, 150, 0.4); }
    .swal2-popup.swal2-toast .swal2-validationerror {
      width: 100%;
      margin: 5px -20px; }
    .swal2-popup.swal2-toast .swal2-success {
      border-color: #a5dc86; }
      .swal2-popup.swal2-toast .swal2-success [class^='swal2-success-circular-line'] {
        border-radius: 50%;
        position: absolute;
        width: 32px;
        height: 64px;
        -webkit-transform: rotate(45deg);
                transform: rotate(45deg); }
        .swal2-popup.swal2-toast .swal2-success [class^='swal2-success-circular-line'][class$='left'] {
          border-radius: 64px 0 0 64px;
          top: -4px;
          left: -15px;
          -webkit-transform: rotate(-45deg);
                  transform: rotate(-45deg);
          -webkit-transform-origin: 32px 32px;
                  transform-origin: 32px 32px; }
        .swal2-popup.swal2-toast .swal2-success [class^='swal2-success-circular-line'][class$='right'] {
          border-radius: 0 64px 64px 0;
          top: -5px;
          left: 14px;
          -webkit-transform-origin: 0 32px;
                  transform-origin: 0 32px; }
      .swal2-popup.swal2-toast .swal2-success .swal2-success-ring {
        width: 32px;
        height: 32px; }
      .swal2-popup.swal2-toast .swal2-success .swal2-success-fix {
        width: 7px;
        height: 90px;
        left: 28px;
        top: 8px; }
      .swal2-popup.swal2-toast .swal2-success [class^='swal2-success-line'] {
        height: 5px; }
        .swal2-popup.swal2-toast .swal2-success [class^='swal2-success-line'][class$='tip'] {
          width: 12px;
          left: 3px;
          top: 18px; }
        .swal2-popup.swal2-toast .swal2-success [class^='swal2-success-line'][class$='long'] {
          width: 22px;
          right: 3px;
          top: 15px; }
    .swal2-popup.swal2-toast .swal2-animate-success-line-tip {
      -webkit-animation: animate-toast-success-tip .75s;
              animation: animate-toast-success-tip .75s; }

In [36]:
for tag in soup.find_all(True):
    print(tag.name)

html
head
meta
meta
meta
title
meta
link
link
link
link
link
link
link
link
link
link
link
link
link
link
link
link
link
img
script
script
script
script
script
script
script
script
script
style
link
script
script
script
script
script
script
noscript
img
script
script
meta
script
style
script
script
link
script
script
body
amp-analytics
script
div
div
header
div
div
div
div
figure
a
img
span
div
div
div
div
div
div
a
span
span
span
span
span
ul
li
a
i
li
a
a
i
span
i
ul
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
i
li
a
i
li
a
i
li
a
i
nav
ul
li
a
i
li
a
i
ul
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
li
a
i
li
a
i
li
a
i
li
a
i
div
div
ul
li
a
i
li
a
i
li
a
i
li
a
i
li
a
i
li
a
i
div
div
div
div
div
div
div
div
div
div
div
figure
img
div
div
div
div
div
div
div
form
div
div
div
div
div
div
div
div
span
div
div
div
div
div
figure
a
img
figcaption
div
ul
li
div
a
i
div
span
div
div
h4
a
span
ul
li
i
span
span
span
small
span
br
div
div
div
figure
a
img
figcaption
div
ul
li
div
a
i
div
span
div
div
h4
a
span
ul
li
i
span
span
span
small
span
br
div
div
div
figure
a
img
figcaption
div
ul
li
div
a
i
div
span
div
div
h4
a
span
ul
li
i
span
span
span
small
span
br
div
div
div
figure
a
img
figcaption
div
ul
li
div
a
i
div
span
div
div
h4
a
span
ul
li
i
span
span
span
small
span
br
div
div
div
figure
a
img
figcaption
div
ul
li
div
a
i
div
span
div
div
h4
a
span
ul
li
i
span
span
span
small
span
br
div
div
div
figure
a
img
figcaption
div
ul
li
div
a
i
div
span
div
div
h4
a
span
ul
li
i
span
span
span
small
span
br
div
div
div
figure
a
img
figcaption
div
ul
li
div
a
i
div
span
div
div
h4
a
span
ul
li
i
span
span
span
small
span
br
div
div
div
figure
a
img
figcaption
div
ul
li
div
a
i
div
span
div
div
h4
a
span
ul
li
i
span
span
span
small
span
br
div
div
div
figure
a
img
figcaption
div
ul
li
div
a
i
div
span
div
div
h4
a
span
ul
li
i
span
span
span
small
span
br
div
div
div
figure
a
img
figcaption
div
ul
li
div
a
i
div
span
div
div
h4
a
span
ul
li
i
span
span
span
small
span
br
div
div
nav
ul
nav
div
span
a
div
div
p
span
span
span
div
span
span
span
svg
path
span
span
a
a
a
svg
path
footer
hr
div
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
div
a
img
hr
div
div
div
div
div
div
label
div
p
span
span
br
span
span
br
div
div
label
ul
li
a
li
a
li
a
li
a
li
a
br
div
div
label
br
a
script
script
a
br
img
br
div
div
ul
li
a
i
li
a
i
li
a
i
li
a
i
li
a
i
li
a
i
hr
div
div
p
a
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
iframe
div
iframe

In [38]:
div_containers = soup.findAll('div', attrs={'class':"property-row col-lg-12 col-md-12 col-sm-12 col-xs-12"})
print(div_containers)

[<div class="property-row col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="property-medium active advance-grid">
<div class="img-holder image-loaded">
<figure>
<a href="https://ubuvilla.com/property/UBU11835"><img alt="#" class="img-grid" src="uploaded/title_villa/0318202504351067d8f7fe50a20WhatsApp Image 2025-03-17 at 13.04.53_4e55bbf2.jpg"/></a>
<figcaption>
<!-- <span class="featured">featured</span> -->
<div class="caption-inner">
<ul class="rem-property-options">
<li class="property-video-opt">
<div class="option-holder">
<a class="property-video-btn" data-rel="prettyPhoto" href="https://www.youtube.com/@ubuvillaindonesia">
<i class="icon-film3"></i>
<div class="option-content"><span>Video</span></div>
</a>
</div>
</li>
</ul>
</div>
</figcaption>
</figure>
</div>
<div class="text-holder">
<div class="post-title">
<h4><a href="https://ubuvilla.com/property/UBU11835">Cooming Soon Ubu Villa Little Haven</a></h4>
</div>
<span class="justify">Ubu Villa Little Haven ...</span>
<ul class="property-location">
<li><i class="icon-location-pin2"></i><span>Jl. Kaliurang No.KM 19, RW.5, Gambiran, Pakembinangun, Kec. Pakem, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55582</span></li>
</ul>
<span class="property-price">
<span style="color:#e67e22; "><small>Start from</small> Rp.1.300.000</span><span class="prop-price-type">
<!--<span class="price-type">| Weekdays</span>-->
</span><br/>
<!--<span>1.600.000K</span><span class="prop-price-type">-->
<!--    <span class="price-type">Weekends Price</span>-->
<!--</span>-->
</span>
<!-- <div class="opening-time">
                                                                                        <ul>
                                                                                            <li>
                                                                                                <span class="time-label">Open House</span>
                                                                                                <small>March 1, 2019 11:00 pm to 06:00 pm</small>
                                                                                            </li>
                                                                                        </ul>
                                                                                    </div> -->
</div>
</div>
</div>, <div class="property-row col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="property-medium active advance-grid">
<div class="img-holder image-loaded">
<figure>
<a href="https://ubuvilla.com/property/UBU13134"><img alt="#" class="img-grid" src="uploaded/title_villa/01312025035013679c4875dd5d7UBU04206.jpg"/></a>
<figcaption>
<!-- <span class="featured">featured</span> -->
<div class="caption-inner">
<ul class="rem-property-options">
<li class="property-video-opt">
<div class="option-holder">
<a class="property-video-btn" data-rel="prettyPhoto" href="https://www.youtube.com/embed/PLdsXOgbiUM?si=Uy-5ztZIhiTJLkB1">
<i class="icon-film3"></i>
<div class="option-content"><span>Video</span></div>
</a>
</div>
</li>
</ul>
</div>
</figcaption>
</figure>
</div>
<div class="text-holder">
<div class="post-title">
<h4><a href="https://ubuvilla.com/property/UBU13134">Ubu Villa Sujiva</a></h4>
</div>
<span class="justify">Ubu Villa Sujiva adalah villa satu kamar yang cocok sekali untuk honeymoon. Terdapat pemandangan sawah indah di halaman belakang dan bathub semi-outdoor untuk pengalaman intim yang berkesan. Tirai outdoor di dekat kolam renang membuat kamu bisa pilih, hendak privasi atau menikmati pemandangan. Di villa ini kamu bisa bersantai di bawah langit berbin ...</span>
<ul class="property-location">
<li><i class="icon-location-pin2"></i><span>Jl Jogopaten, Pandowoharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta, Sleman, Daerah Istimewa Yogyakarta 55581</span></li>
</ul>
<span class="property-price">
<span style="color:#e67e22; "><small>Start from</small> Rp.900.000</span><span class="prop-price-type">
<!--<span class="price-type">| Weekdays</span>-->
</span><br/>
<!--<span>1.200.000K</span><span class="prop-price-type">-->
<!--    <span class="price-type">Weekends Price</span>-->
<!--</span>-->
</span>
<!-- <div class="opening-time">
                                                                                        <ul>
                                                                                            <li>
                                                                                                <span class="time-label">Open House</span>
                                                                                                <small>March 1, 2019 11:00 pm to 06:00 pm</small>
                                                                                            </li>
                                                                                        </ul>
                                                                                    </div> -->
</div>
</div>
</div>, <div class="property-row col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="property-medium active advance-grid">
<div class="img-holder image-loaded">
<figure>
<a href="https://ubuvilla.com/property/UBU10232"><img alt="#" class="img-grid" src="uploaded/title_villa/12022024022924674d1b84b175aFile-6.jpg"/></a>
<figcaption>
<!-- <span class="featured">featured</span> -->
<div class="caption-inner">
<ul class="rem-property-options">
<li class="property-video-opt">
<div class="option-holder">
<a class="property-video-btn" data-rel="prettyPhoto" href="https://www.youtube.com/embed/MQGCVbdgjUA?si=YuMfked7OXxbwaEl">
<i class="icon-film3"></i>
<div class="option-content"><span>Video</span></div>
</a>
</div>
</li>
</ul>
</div>
</figcaption>
</figure>
</div>
<div class="text-holder">
<div class="post-title">
<h4><a href="https://ubuvilla.com/property/UBU10232">Ubu Villa Redwood</a></h4>
</div>
<span class="justify">Ubu Villa Kinanthi Redwood, tempat kamu bisa ngerasain vibes kehidupan ala Norwegia-Swedia. Cat merah iconicnya jadi simbol kekayaan dan status sosial, membuat suasana pedesaan jadi cozy dan penuh nostalgia. Dengan dua kamar tidur yang nyaman dan dekorasi khas Norway-Swedia, kamu akan sangat betah. Ada sungai kecil yang mengalir di halaman, membuat ...</span>
<ul class="property-location">
<li><i class="icon-location-pin2"></i><span>Donomulyo, Donokerto, Kec. Turi, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55551</span></li>
</ul>
<span class="property-price">
<span style="color:#e67e22; "><small>Start from</small> Rp.1.300.000</span><span class="prop-price-type">
<!--<span class="price-type">| Weekdays</span>-->
</span><br/>
<!--<span>1.600.000K</span><span class="prop-price-type">-->
<!--    <span class="price-type">Weekends Price</span>-->
<!--</span>-->
</span>
<!-- <div class="opening-time">
                                                                                        <ul>
                                                                                            <li>
                                                                                                <span class="time-label">Open House</span>
                                                                                                <small>March 1, 2019 11:00 pm to 06:00 pm</small>
                                                                                            </li>
                                                                                        </ul>
                                                                                    </div> -->
</div>
</div>
</div>, <div class="property-row col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="property-medium active advance-grid">
<div class="img-holder image-loaded">
<figure>
<a href="https://ubuvilla.com/property/UBU12231"><img alt="#" class="img-grid" src="uploaded/title_villa/10142024075038670ccd4e9bdcaFile Edit-174_10_11zon.jpg"/></a>
<figcaption>
<!-- <span class="featured">featured</span> -->
<div class="caption-inner">
<ul class="rem-property-options">
<li class="property-video-opt">
<div class="option-holder">
<a class="property-video-btn" data-rel="prettyPhoto" href="https://www.youtube.com/embed/8opxI-N7_WA?si=cUE0euoYKNYwevOZ">
<i class="icon-film3"></i>
<div class="option-content"><span>Video</span></div>
</a>
</div>
</li>
</ul>
</div>
</figcaption>
</figure>
</div>
<div class="text-holder">
<div class="post-title">
<h4><a href="https://ubuvilla.com/property/UBU12231">Ubu Villa Amarta</a></h4>
</div>
<span class="justify">Ubu Villa Amarta, "Javanese Charm, Timeless Elegance", adalah villa klasik yang bukan sekedar kenyamanan—tapi juga momen magis. Terletak di pinggir kota, villa ini menyuguhkan pemandangan Gunung Merapi dan hamparan hijau yang asri. Menghadap ke timur, kamu bisa menikmati momen matahari terbit yang indah langsung dari kamar. Detail ukiran tradisio ...</span>
<ul class="property-location">
<li><i class="icon-location-pin2"></i><span>Jl. Karangtanjung, Karang Kepuh, Pandowoharjo, Sleman, Daerah Istimewa Yogyakarta</span></li>
</ul>
<span class="property-price">
<span style="color:#e67e22; "><small>Start from</small> Rp.1.400.000</span><span class="prop-price-type">
<!--<span class="price-type">| Weekdays</span>-->
</span><br/>
<!--<span>1.700.000K</span><span class="prop-price-type">-->
<!--    <span class="price-type">Weekends Price</span>-->
<!--</span>-->
</span>
<!-- <div class="opening-time">
                                                                                        <ul>
                                                                                            <li>
                                                                                                <span class="time-label">Open House</span>
                                                                                                <small>March 1, 2019 11:00 pm to 06:00 pm</small>
                                                                                            </li>
                                                                                        </ul>
                                                                                    </div> -->
</div>
</div>
</div>, <div class="property-row col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="property-medium active advance-grid">
<div class="img-holder image-loaded">
<figure>
<a href="https://ubuvilla.com/property/UBU11830"><img alt="#" class="img-grid" src="uploaded/title_villa/0418202403584766209a779c2a7UBU09342.jpg"/></a>
<figcaption>
<!-- <span class="featured">featured</span> -->
<div class="caption-inner">
<ul class="rem-property-options">
<li class="property-video-opt">
<div class="option-holder">
<a class="property-video-btn" data-rel="prettyPhoto" href="https://www.youtube.com/embed/UcCN5DxwfyA?si=zbNRylwjG7P2nA1d">
<i class="icon-film3"></i>
<div class="option-content"><span>Video</span></div>
</a>
</div>
</li>
</ul>
</div>
</figcaption>
</figure>
</div>
<div class="text-holder">
<div class="post-title">
<h4><a href="https://ubuvilla.com/property/UBU11830">Ubu Villa Padi's</a></h4>
</div>
<span class="justify">Ubu Villa Padi's menawarkan pemandangan sawah yang indah dengan perpaduan konsep Bali-Jepang yang estetik dan suasana yang nyaman. Saat memasuki villa, Ubu Lovers akan langsung disambut oleh kolam dengan beragam ikan hias yang warna-warni. Villa 1 kamar ini juga menyajikan pemandangan padi yang menakjubkan di area private poolnya. Nikmati momen ber ...</span>
<ul class="property-location">
<li><i class="icon-location-pin2"></i><span>Jl. Donoloyo, Jogopaten, Pandowoharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta</span></li>
</ul>
<span class="property-price">
<span style="color:#e67e22; "><small>Start from</small> Rp.900.000</span><span class="prop-price-type">
<!--<span class="price-type">| Weekdays</span>-->
</span><br/>
<!--<span>1.200.000K</span><span class="prop-price-type">-->
<!--    <span class="price-type">Weekends Price</span>-->
<!--</span>-->
</span>
<!-- <div class="opening-time">
                                                                                        <ul>
                                                                                            <li>
                                                                                                <span class="time-label">Open House</span>
                                                                                                <small>March 1, 2019 11:00 pm to 06:00 pm</small>
                                                                                            </li>
                                                                                        </ul>
                                                                                    </div> -->
</div>
</div>
</div>, <div class="property-row col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="property-medium active advance-grid">
<div class="img-holder image-loaded">
<figure>
<a href="https://ubuvilla.com/property/UBU12929"><img alt="#" class="img-grid" src="uploaded/title_villa/032920240427046606431881e71Edit-49.JPG"/></a>
<figcaption>
<!-- <span class="featured">featured</span> -->
<div class="caption-inner">
<ul class="rem-property-options">
<li class="property-video-opt">
<div class="option-holder">
<a class="property-video-btn" data-rel="prettyPhoto" href="https://www.youtube.com/embed/pP6e7kuvM_0?si=dSVHFGZ_B0iJEmB_">
<i class="icon-film3"></i>
<div class="option-content"><span>Video</span></div>
</a>
</div>
</li>
</ul>
</div>
</figcaption>
</figure>
</div>
<div class="text-holder">
<div class="post-title">
<h4><a href="https://ubuvilla.com/property/UBU12929">Ubu Villa California</a></h4>
</div>
<span class="justify">Ubu Villa California adalah ruang berlibur pribadi dengan nuansa hijau ala klasik Amerika. Berlokasi di utara Jogja, Ubu Lovers dapat menjelajahi beragam jenis atraksi di kota. Villa dengan 2 kamar ini sangat nyaman untuk keluarga kecil. Villa ini juga mempunyai bathtub dan microwave untuk menambah kesan modern. Ubu Lovers bisa bersantai di area li ...</span>
<ul class="property-location">
<li><i class="icon-location-pin2"></i><span>Jl. Panca Marga No.05, RT.05/RW.22, Jatirejo, Sendangadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta</span></li>
</ul>
<span class="property-price">
<span style="color:#e67e22; "><small>Start from</small> Rp.1.400.000</span><span class="prop-price-type">
<!--<span class="price-type">| Weekdays</span>-->
</span><br/>
<!--<span>1.700.000K</span><span class="prop-price-type">-->
<!--    <span class="price-type">Weekends Price</span>-->
<!--</span>-->
</span>
<!-- <div class="opening-time">
                                                                                        <ul>
                                                                                            <li>
                                                                                                <span class="time-label">Open House</span>
                                                                                                <small>March 1, 2019 11:00 pm to 06:00 pm</small>
                                                                                            </li>
                                                                                        </ul>
                                                                                    </div> -->
</div>
</div>
</div>, <div class="property-row col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="property-medium active advance-grid">
<div class="img-holder image-loaded">
<figure>
<a href="https://ubuvilla.com/property/UBU11928"><img alt="#" class="img-grid" src="uploaded/title_villa/06272024075433667d1ab93e8cfEdit-31.JPG"/></a>
<figcaption>
<!-- <span class="featured">featured</span> -->
<div class="caption-inner">
<ul class="rem-property-options">
<li class="property-video-opt">
<div class="option-holder">
<a class="property-video-btn" data-rel="prettyPhoto" href="https://www.youtube.com/embed/hmzBJ0XYMqw?si=xrJuBZgjc3-WzgTY">
<i class="icon-film3"></i>
<div class="option-content"><span>Video</span></div>
</a>
</div>
</li>
</ul>
</div>
</figcaption>
</figure>
</div>
<div class="text-holder">
<div class="post-title">
<h4><a href="https://ubuvilla.com/property/UBU11928">Ubu Villa Nara</a></h4>
</div>
<span class="justify">Villa Nara adalah sebuah komunal villa yang terdiri dari 9 unit, mengusung tema Bohemian modern minimalis yang bernuansa boho bliss, menyampaikan pengalaman menginap yang menyenangkan. Setiap unit villa Nara menawarkan satu kamar yang sempurna untuk honeymoon, dilengkapi dengan kolam private pool dan bathub. Dengan pemandangan sungai yang menakjubk ...</span>
<ul class="property-location">
<li><i class="icon-location-pin2"></i><span>Pencar Sari, Sardonoharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581</span></li>
</ul>
<span class="property-price">
<span style="color:#e67e22; "><small>Start from</small> Rp.900.000</span><span class="prop-price-type">
<!--<span class="price-type">| Weekdays</span>-->
</span><br/>
<!--<span>1.200.000K</span><span class="prop-price-type">-->
<!--    <span class="price-type">Weekends Price</span>-->
<!--</span>-->
</span>
<!-- <div class="opening-time">
                                                                                        <ul>
                                                                                            <li>
                                                                                                <span class="time-label">Open House</span>
                                                                                                <small>March 1, 2019 11:00 pm to 06:00 pm</small>
                                                                                            </li>
                                                                                        </ul>
                                                                                    </div> -->
</div>
</div>
</div>, <div class="property-row col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="property-medium active advance-grid">
<div class="img-holder image-loaded">
<figure>
<a href="https://ubuvilla.com/property/UBU11827"><img alt="#" class="img-grid" src="uploaded/title_villa/06272024074244667d17f4259b8Katalog (5) (1).JPG"/></a>
<figcaption>
<!-- <span class="featured">featured</span> -->
<div class="caption-inner">
<ul class="rem-property-options">
<li class="property-video-opt">
<div class="option-holder">
<a class="property-video-btn" data-rel="prettyPhoto" href="https://www.youtube.com/embed/c9zj-csKO6I?si=h3yAWY3QDUd-cLF">
<i class="icon-film3"></i>
<div class="option-content"><span>Video</span></div>
</a>
</div>
</li>
</ul>
</div>
</figcaption>
</figure>
</div>
<div class="text-holder">
<div class="post-title">
<h4><a href="https://ubuvilla.com/property/UBU11827">Ubu Villa Amara</a></h4>
</div>
<span class="justify">Ubu Villa Amara adalah sebuah perpaduan tropical antara desain minimalis dengan suasana harmonis. Dengan konsep alami, terang, dan terbuka, villa ini memberikan pengalaman menginap yang menakjubkan di tengah suasana pedesaan yang segar nan menyejukkan. Villa dengan 1 kamar di Jogja ini ideal untuk berbulan madu, Ubu Villa Amara juga memiliki ruang  ...</span>
<ul class="property-location">
<li><i class="icon-location-pin2"></i><span>Jl. Kembangan - Rejodani Jl. Bulus Lor No.1, Bulus I, Candibinangun, Kec. Pakem, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581</span></li>
</ul>
<span class="property-price">
<span style="color:#e67e22; "><small>Start from</small> Rp.900.000</span><span class="prop-price-type">
<!--<span class="price-type">| Weekdays</span>-->
</span><br/>
<!--<span>1.200.000K</span><span class="prop-price-type">-->

## One Page

In [39]:
hotel_name = [] # list kosong
for container in div_containers:
    name = container.find('div', attrs={"class":'post-title'}).text
    print(name) # ngeluarin nilai
    hotel_name.append((name)) # bathroom_villa -> json list
# Parser html documents
hotel_name = pd.DataFrame(hotel_name, columns=['nama'])
hotel_name

Cooming Soon Ubu Villa Little Haven


Ubu Villa Sujiva


Ubu Villa Redwood


Ubu Villa Amarta


Ubu Villa Padi's


Ubu Villa California


Ubu Villa Nara


Ubu Villa Amara


Ubu Villa Alston


Ubu Villa Kinanthi

                                      nama
0  \nCooming Soon Ubu Villa Little Haven\n
1                     \nUbu Villa Sujiva\n
2                    \nUbu Villa Redwood\n
3                     \nUbu Villa Amarta\n
4                     \nUbu Villa Padi's\n
5                 \nUbu Villa California\n
6                       \nUbu Villa Nara\n
7                      \nUbu Villa Amara\n
8                     \nUbu Villa Alston\n
9                   \nUbu Villa Kinanthi\n

## Multiple Page

In [40]:
for page in range(1, 4):  # Mengiterasi melalui 4 halaman
    url = f'https://ubuvilla.com/property?page={page}'
    print(url)

https://ubuvilla.com/property?page=1
https://ubuvilla.com/property?page=2
https://ubuvilla.com/property?page=3

In [41]:
titles = []  # List untuk menyimpan judul

for page in range(1, 4):  # Mengiterasi melalui 4 halaman
    url = f'https://ubuvilla.com/property?page={page}'
  # Ganti URL dengan URL sebenarnya
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser') # Parser html documents
    #code diatas ialah untuk multiple page

    #define container terluar
    div_containers = soup.findAll('div', attrs={'class':"property-row col-lg-12 col-md-12 col-sm-12 col-xs-12"})

    for container in div_containers:
        review = container.find('div', attrs={'class': 'post-title'})
        if review:
            titles.append(review.text.strip())

# Membuat dataframe dari list judul
df_villa_title = pd.DataFrame({'title': titles})
print('total properties yang didapat : ', len(df_villa_title)) #validation data
# Menampilkan dataframe
df_villa_title.head()

total properties yang didapat :  23

                                 title
0  Cooming Soon Ubu Villa Little Haven
1                     Ubu Villa Sujiva
2                    Ubu Villa Redwood
3                     Ubu Villa Amarta
4                     Ubu Villa Padi's

In [42]:
df_villa_title

                                  title
0   Cooming Soon Ubu Villa Little Haven
1                      Ubu Villa Sujiva
2                     Ubu Villa Redwood
3                      Ubu Villa Amarta
4                      Ubu Villa Padi's
5                  Ubu Villa California
6                        Ubu Villa Nara
7                       Ubu Villa Amara
8                      Ubu Villa Alston
9                    Ubu Villa Kinanthi
10              Ubu Villa  Ndalem Etnik
11                  Ubu Villa Marrakech
12                    Ubu Villa Coconut
13                  Ubu Villa Tropicola
14                  Ubu Villa Prambanan
15                     Ubu Villa Blekik
16                   Ubu Villa Balirejo
17                  Ubu Villa Gito Gati
18                  Ubu Villa Donolayan
19            Dalem jongke By Ubu Villa
20                 Ubu Villa Pulowatu 1
21                 Ubu Villa Pulowatu 2
22                 Ubu Villa Pulowatu 3

In [44]:
address = []  # List untuk menyimpan judul

for page in range(1, 4):  # Mengiterasi melalui 4 halaman
    url = f'https://ubuvilla.com/property?page={page}'
  # Ganti URL dengan URL sebenarnya
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser') # Parser html documents
    #code diatas ialah untuk multiple page

    #define container terluar
    div_containers = soup.findAll('div', attrs={'class':"property-row col-lg-12 col-md-12 col-sm-12 col-xs-12"})

    for container in div_containers:
        review = container.find('ul', attrs={'class': 'property-location'})
        if review:
            address.append(review.text.strip())

# Membuat dataframe dari list judul
df_villa_address = pd.DataFrame({'address': address})
print('total properties yang didapat : ', len(df_villa_address)) #validation data
# Menampilkan dataframe
df_villa_address.head()

total properties yang didapat :  23

                                                                                                                           address
0            Jl. Kaliurang No.KM 19, RW.5, Gambiran, Pakembinangun, Kec. Pakem, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55582
1  Jl Jogopaten, Pandowoharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta, Sleman, Daerah Istimewa Yogyakarta 55581
2                                              Donomulyo, Donokerto, Kec. Turi, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55551
3                                                Jl. Karangtanjung, Karang Kepuh, Pandowoharjo, Sleman, Daerah Istimewa Yogyakarta
4                                 Jl. Donoloyo, Jogopaten, Pandowoharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta

In [45]:
df_villa_address

                                                                                                                                      address
0                       Jl. Kaliurang No.KM 19, RW.5, Gambiran, Pakembinangun, Kec. Pakem, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55582
1             Jl Jogopaten, Pandowoharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta, Sleman, Daerah Istimewa Yogyakarta 55581
2                                                         Donomulyo, Donokerto, Kec. Turi, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55551
3                                                           Jl. Karangtanjung, Karang Kepuh, Pandowoharjo, Sleman, Daerah Istimewa Yogyakarta
4                                            Jl. Donoloyo, Jogopaten, Pandowoharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta
5                          Jl. Panca Marga No.05, RT.05/RW.22, Jatirejo, Sendangadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta
6                                                 Pencar Sari, Sardonoharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581
7         Jl. Kembangan - Rejodani Jl. Bulus Lor No.1, Bulus I, Candibinangun, Kec. Pakem, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581
8   Sanggrahan Jl. Raya Pringgodani No.477, RT.04/RW.34, Malangrejo, Wedomartani, Kec. Ngemplak, Kabupaten Sleman, Daerah Istimewa Yogyakarta
9                                                         Donomulyo, Donokerto, Kec. Turi, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55551
10                                              Gg. Melati No.123, Mantrijeron, Kec. Mantrijeron, Kota Yogyakarta, Daerah Istimewa Yogyakarta
11                                           Jl. Kabupaten No.17, Salakan, Trihanggo, Kec. Gamping,, Sleman, Daerah Istimewa Yogyakarta 55591
12                                      Jl. Pandhawa, Tegal Rejo, Sariharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581
13                            Jl. Kapulogo Nologaten, Nologaten, Caturtunggal, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55281
14                                      Jl. Pulerejo, Kranggan, Bokoharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55572
15                                                     Pencar Sari, Sardonoharjo, Ngaglik, Sleman Regency, Special Region of Yogyakarta 55581
16                                                              Jl. Balirejo no.2, RT 021/007, Kel.Muja-Muju, Kec.Umbulherjo, Kota Yogyakarta
17                              Jl. Griya Taman Asri, Berkisan, Pandowoharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55512
18               Jl. Palagan Tentara Pelajar No.Km 11, Donolayan, Donoharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581
19                                                                                          Jln Jongke Tengah, Sendangadi, Mlati, Sleman, DIY
20                                                                                       Jln Pulowatu, Bunder, Purwobinagun, Pakem Sleman DIY
21                                                                                       Jln Pulowatu, Bunder, Purwobinagun, Pakem Sleman DIY
22                                                                                       Jln Pulowatu, Bunder, Purwobinagun, Pakem Sleman DIY

In [46]:
price = []  # List untuk menyimpan judul

for page in range(1, 4):  # Mengiterasi melalui 4 halaman
    url = f'https://ubuvilla.com/property?page={page}'
  # Ganti URL dengan URL sebenarnya
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser') # Parser html documents
    #code diatas ialah untuk multiple page

    #define container terluar
    div_containers = soup.findAll('div', attrs={'class':"property-row col-lg-12 col-md-12 col-sm-12 col-xs-12"})

    for container in div_containers:
        review = container.find('span', attrs={'class': 'property-price'})
        if review:
            price.append(review.text.strip())

# Membuat dataframe dari list judul
df_villa_price = pd.DataFrame({'price': price})
print('total properties yang didapat : ', len(df_villa_price)) #validation data
# Menampilkan dataframe
df_villa_price.head()

total properties yang didapat :  23

                     price
0  Start from Rp.1.300.000
1    Start from Rp.900.000
2  Start from Rp.1.300.000
3  Start from Rp.1.400.000
4    Start from Rp.900.000

In [47]:
df_villa_price

                      price
0   Start from Rp.1.300.000
1     Start from Rp.900.000
2   Start from Rp.1.300.000
3   Start from Rp.1.400.000
4     Start from Rp.900.000
5   Start from Rp.1.400.000
6     Start from Rp.900.000
7     Start from Rp.900.000
8   Start from Rp.1.400.000
9     Start from Rp.900.000
10  Start from Rp.1.000.000
11  Start from Rp.1.400.000
12    Start from Rp.900.000
13  Start from Rp.2.100.000
14  Start from Rp.1.900.000
15  Start from Rp.1.900.000
16  Start from Rp.1.900.000
17  Start from Rp.2.600.000
18  Start from Rp.1.900.000
19  Start from Rp.3.150.000
20    Start from Rp.900.000
21  Start from Rp.2.400.000
22  Start from Rp.1.900.000

In [51]:
url1 = "https://ubuvilla.com"
driver1 = webdriver.Firefox()
driver1.get(url1)

soup = BeautifulSoup(driver1.page_source, "html.parser")

In [57]:
div_containers1 = soup.findAll('ul', attrs={'class':"post-category-list"})
print(div_containers1)

[<ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           2                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            2                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            4
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           1                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            1                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            2
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           2                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            3                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            4
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           1                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            1                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            2
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           1                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            1                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            2
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           2                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            2                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            4
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           1                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            1                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            2
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           1                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            1                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            2
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           2                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            2                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            4
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           2                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            1                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            2
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           1                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            1                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            2
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           2                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            2                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            4
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           1                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            1                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            2
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           3                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            4                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            6
                                                                                            Person
                                                                                        </li>
</ul>, <ul class="post-category-list">
<li> <i class="icon-bed2"></i>
                                                                                             Bedrooms
                                                                                           3                                                                                        </li>
<li> <i class="icon-man-woman"></i>
                                                                                             Bathrooms
                                                                                            3                                                                                        </li>
<li> <i class="icon-directions_car"></i>
                                                                                             Parking Lot
                                                                                        </li>
<li> <i class="icon-users"></i>
                                                                                             Capacity
                                                                                            6

In [ ]:
villa_details = []

for ul in div_containers1:
    detail = {}

    # Bedrooms
    bed = ul.find('i', class_='icon-bed2')
    if bed:
        li = bed.find_parent('li')
        text = li.get_text(strip=True)
        match = re.search(r'\d+(\/\d+)?', text)
        detail['Bedrooms'] = match.group(0) if match else None
    else:
        detail['Bedrooms'] = None

    # Bathrooms
    bath = ul.find('i', class_='icon-man-woman')
    if bath:
        li = bath.find_parent('li')
        text = li.get_text(strip=True)
        match = re.search(r'\d+(\/\d+)?', text)
        detail['Bathrooms'] = match.group(0) if match else None
    else:
        detail['Bathrooms'] = None

    # Parking
    detail['Parking'] = 'Yes' if ul.find('i', class_='icon-directions_car') else 'No'

    # Capacity
    cap = ul.find('i', class_='icon-users')
    if cap:
        li = cap.find_parent('li')
        text = li.get_text(strip=True)
        match = re.search(r'\d+(\/\d+)?', text)
        detail['Capacity'] = match.group(0) if match else None
    else:
        detail['Capacity'] = None

    villa_details.append(detail)

df_villa_details = pd.DataFrame(villa_details)
print(f"Total villas extracted: {len(df_villa_details)}")
df_villa_details.head()

Total villas extracted: 23

  Bedrooms Bathrooms Parking Capacity
0        2         2     Yes        4
1        1         1     Yes        2
2        2         3     Yes        4
3        1         1     Yes        2
4        1         1     Yes        2

In [70]:
df_villas = pd.concat([df_villa_title, df_villa_address, df_villa_price, df_villa_details], axis=1)
print('total properties yang didapat : ', len(df_villas))
df_villas.head()

total properties yang didapat :  23

,title,address,price,Bedrooms,Bathrooms,Parking,Capacity
0,Cooming Soon Ubu Villa Little Haven,"Jl. Kaliurang No.KM 19, RW.5, Gambiran, Pakembinangun, Kec. Pakem, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55582",Start from Rp.1.300.000,2,2,Yes,4
1,Ubu Villa Sujiva,"Jl Jogopaten, Pandowoharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta, Sleman, Daerah Istimewa Yogyakarta 55581",Start from Rp.900.000,1,1,Yes,2
2,Ubu Villa Redwood,"Donomulyo, Donokerto, Kec. Turi, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55551",Start from Rp.1.300.000,2,3,Yes,4
3,Ubu Villa Amarta,"Jl. Karangtanjung, Karang Kepuh, Pandowoharjo, Sleman, Daerah Istimewa Yogyakarta",Start from Rp.1.400.000,1,1,Yes,2
4,Ubu Villa Padi's,"Jl. Donoloyo, Jogopaten, Pandowoharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta",Start from Rp.900.000,1,1,Yes,2

## Cleaning

In [71]:
df_villas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      23 non-null     object
 1   address    23 non-null     object
 2   price      23 non-null     object
 3   Bedrooms   23 non-null     object
 4   Bathrooms  23 non-null     object
 5   Parking    23 non-null     object
 6   Capacity   23 non-null     object
dtypes: object(7)
memory usage: 1.4+ KB

In [79]:
df_villas['Price'] = (
    df_villas['price']
    .str.extract(r'Rp\.([\d.]+)')[0]
    .str.replace('.', '', regex=False)
    .astype(float)
)
df_villas.head()

,title,address,price,Bedrooms,Bathrooms,Parking,Capacity,Price
0,Cooming Soon Ubu Villa Little Haven,"Jl. Kaliurang No.KM 19, RW.5, Gambiran, Pakembinangun, Kec. Pakem, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55582",Start from Rp.1.300.000,2,2,Yes,4,1300000.0
1,Ubu Villa Sujiva,"Jl Jogopaten, Pandowoharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta, Sleman, Daerah Istimewa Yogyakarta 55581",Start from Rp.900.000,1,1,Yes,2,900000.0
2,Ubu Villa Redwood,"Donomulyo, Donokerto, Kec. Turi, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55551",Start from Rp.1.300.000,2,3,Yes,4,1300000.0
3,Ubu Villa Amarta,"Jl. Karangtanjung, Karang Kepuh, Pandowoharjo, Sleman, Daerah Istimewa Yogyakarta",Start from Rp.1.400.000,1,1,Yes,2,1400000.0
4,Ubu Villa Padi's,"Jl. Donoloyo, Jogopaten, Pandowoharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta",Start from Rp.900.000,1,1,Yes,2,900000.0

In [80]:
df_villas.to_csv("villa_data.csv", index=False)